<?php /* KohandezhCV — portfolio page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!doctype html>
<html data-kdcv-i18n="in-place" lang="fa" dir="rtl" data-kdcv-router-mode="wordpress" data-kdcv-site-base="<?php echo esc_url(home_url('/')); ?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Portfolio | Mohammad Ali Kohandezh</title>
  <meta name="description" content="Selected organizations and enterprise engagements from Mohammad Ali Kohandezh's technology portfolio.">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <meta name="theme-color" content="#080b0f">
  <link rel="canonical" href="<?php echo esc_url( home_url('/portfolio/') ); ?>">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@kohandezh">
  <meta name="twitter:title" content="Portfolio | Mohammad Ali Kohandezh">
  <meta name="twitter:description" content="Selected organizations and enterprise engagements from Mohammad Ali Kohandezh&#x27;s technology portfolio.">
  <meta name="twitter:image" content="<?php echo KDCV; ?>/assets/images/avatar/avatar-professional.webp">
  <link rel="icon" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2026091701" sizes="32x32">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/fonts.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/portfolio.min.css?v=2026091705">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/shiny-button.min.css?v=2026091705">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=2026091705">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/hud-button.min.css?v=2026091705">
  <?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=2026091705" media="print" onload="this.media='all'"><?php endif; ?><noscript><?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=2026091705"><?php endif; ?></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=2026091705" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=2026091705"></noscript>
  <!-- Breadcrumb trail: lets Google render the path instead of a bare
       URL in results, and gives answer engines the page's place in the
       site rather than treating it as an orphan. -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "خانه",
      "item": "https://kohandezh.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Portfolio",
      "item": "https://kohandezh.com/portfolio/"
    }
  ]
}
  </script>
    <?php wp_head(); ?>
</head>
<body>
<?php wp_body_open(); ?>
<!-- WAITING:BEGIN generated from _tooling/waiting/waiting.partial.html by _tooling/waiting/build.py -- do not edit by hand -->
<style>
#kdcv-waiting{--kw-bg:#ebebeb;--kw-ink:#0a7233;--kw-trk:rgba(10,114,51,.14);position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;background:var(--kw-bg);animation:kdcvw-h .4s 6s forwards}
#kdcv-waiting.kdcv-waiting-dk,html[data-kdcv-theme=dark] #kdcv-waiting{--kw-bg:#0f0f0f;--kw-ink:#a8ff46;--kw-trk:rgba(240,255,222,.12)}
html[data-kdcv-theme=light] #kdcv-waiting{--kw-bg:#ebebeb;--kw-ink:#0a7233;--kw-trk:rgba(10,114,51,.14)}
.kdcv-waiting-out{opacity:0;visibility:hidden;pointer-events:none;transition:opacity .36s .26s,visibility 0s .62s}
.kdcv-waiting-r.kdcv-waiting-out{transition:opacity .2s,visibility 0s .2s}
#kdcv-waiting svg{width:clamp(96px,24vmin,132px);height:auto;overflow:visible}
.kdcvw-t{stroke:var(--kw-trk)}
.kdcvw-c,.kdcvw-f{stroke:var(--kw-ink)}
.kdcvw-c{stroke-dasharray:487 1542}
.kdcvw-f{stroke-dasharray:2029;stroke-dashoffset:2029;opacity:0}
.kdcv-waiting-out .kdcvw-c{opacity:0;transition:opacity .15s}
.kdcv-waiting-out .kdcvw-f{opacity:1;stroke-dashoffset:0;transition:stroke-dashoffset .36s cubic-bezier(.65,0,.35,1)}
@media (prefers-reduced-motion:no-preference){
#kdcv-waiting svg{animation:kdcvw-in .5s cubic-bezier(.2,.8,.2,1) both}
.kdcvw-c{animation:kdcvw-run 1.4s linear infinite}
.kdcvw-a{animation:kdcvw-p 2.8s ease-in-out infinite}
.kdcv-waiting-r svg{animation:none}
}
@media (prefers-reduced-motion:reduce){.kdcvw-c,.kdcvw-f{display:none}}
@keyframes kdcvw-h{from{pointer-events:none}to{opacity:0;visibility:hidden;pointer-events:none}}
@keyframes kdcvw-in{from{opacity:0;transform:scale(.9)}}
@keyframes kdcvw-run{to{stroke-dashoffset:-2029}}
@keyframes kdcvw-p{50%{opacity:.6}}
</style>
<noscript><style>#kdcv-waiting{display:none}</style></noscript>
<div id="kdcv-waiting" role="progressbar" aria-label="Loading"><svg viewBox="-40 -40 592 592" aria-hidden="true"><defs><linearGradient id="kdcvw-tile" x1="0" y1="0" x2="512" y2="512" gradientUnits="userSpaceOnUse"><stop stop-color="#171D1B"/><stop offset="1" stop-color="#050807"/></linearGradient><linearGradient id="kdcvw-accent" x1="200" y1="270" x2="255" y2="380" gradientUnits="userSpaceOnUse"><stop stop-color="#D9FF8A"/><stop offset="1" stop-color="#4FD35F"/></linearGradient></defs><g fill="none" stroke-width="12" stroke-linecap="round"><rect class="kdcvw-t" x="-28" y="-28" width="568" height="568" rx="142"/><rect class="kdcvw-c" x="-28" y="-28" width="568" height="568" rx="142"/><rect class="kdcvw-f" x="-28" y="-28" width="568" height="568" rx="142"/></g><rect width="512" height="512" rx="114" fill="url(#kdcvw-tile)"/><path class="kdcvw-a" d="M262 268 205 380 258 380 258 268Z" fill="url(#kdcvw-accent)"/><g fill="none" stroke="#F0FFDE" stroke-width="46" stroke-linecap="round" stroke-linejoin="round"><path d="M126 372V174l79 100 79-100v198"/><path d="M284 268 396 156M284 268l112 112"/></g></svg></div>
<script>(function(){var d=document,w=window,h=d.documentElement,e=d.getElementById("kdcv-waiting"),T=setTimeout,D=Date.now,t0=D(),ti,n,f,t,m,M,C;if(!e)return;
function k(){n=1;e.remove()}
function o(){n||(n=1,e.className+=" kdcv-waiting-out",T(k,f?680:260))}
function q(s){try{return matchMedia(s).matches}catch(x){}}
function a(y,z,p){w.addEventListener(y,z,p)}
if(/bot|crawl|spider|slurp|facebookexternalhit/i.test(navigator.userAgent)||d.readyState=="complete")return k();
try{t=sessionStorage;f=!t.getItem("kdcvWaitingSeen");t.setItem("kdcvWaitingSeen",1)}catch(x){}
try{t=h.getAttribute("data-kdcv-theme");if(!t){try{m=localStorage.getItem("darkMode")}catch(x){}t=m!=null?m=="enabled"?"dark":"light":d.body.dataset.defaultMode||(q("(prefers-color-scheme:dark)")?"dark":"light")}
e.className+=(t=="dark"?" kdcv-waiting-dk":"")+(f?"":" kdcv-waiting-r");
t={fa:"در حال بارگذاری",ar:"جارٍ التحميل",de:"Wird geladen",es:"Cargando",fr:"Chargement",tr:"Yükleniyor",zh:"加载中",ja:"読み込み中",ru:"Загрузка"}[h.lang.slice(0,2)];t&&e.setAttribute("aria-label",t)}catch(x){}
M=f&&!q("(prefers-reduced-motion:reduce)")?940:0;C=f?1200:0;
function g(){var z=D();z-t0<M||!(d.readyState=="complete"||ti&&z-ti>=C||z-t0>=3e3)||o()}
function i(){ti=ti||D();g();T(g,C)}
a("keydown",o,!0);a("pointerdown",o,!0);a("pageshow",function(v){v.persisted&&k()});
d.addEventListener("load",g,!0);d.readyState=="loading"?d.addEventListener("readystatechange",i):i();T(g,M);T(g,3e3)})()</script>
<!-- WAITING:END -->
<script>/* Theme boot — runs before paint so a page never flashes the wrong theme on navigation. Mirrors main.js: stored choice wins, then data-default-mode, then light. `light` is the class portfolio.js uses. */(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <a class="skip-link" href="#clients" data-i18n="skip">رفتن به نمونه‌کارها</a>
  <header class="portfolio-header">
    <a class="portfolio-brand" href="/" aria-label="Kohandezh home">
      <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="42" height="42" alt="">
      <span><b>KOHANDEZH</b><small>Enterprise portfolio</small></span>
    </a>
    <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
        <div class="portfolio-actions" aria-label="Page settings">
      <button class="portfolio-control" id="themeToggle" type="button" aria-label="حالت نمایش" title="حالت نمایش">
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3v2m0 14v2M3 12h2m14 0h2M5.64 5.64l1.42 1.42m9.88 9.88 1.42 1.42m0-12.72-1.42 1.42M7.06 16.94l-1.42 1.42M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
      </button>
      <label class="portfolio-control language-wrap" aria-label="زبان" title="زبان"><span class="language-label" id="languageLabel">FA</span><select id="languageSelect"><option value="fa">فارسی</option><option value="en">English</option><option value="ar">العربية</option><option value="de">Deutsch</option><option value="es">Español</option><option value="fr">Français</option><option value="tr">Türkçe</option><option value="zh">中文</option><option value="ja">日本語</option>
              <option value="ru">Русский</option></select></label>
      <a class="portfolio-home" href="/" data-i18n-aria="home"><span data-i18n="home">بازگشت به رزومه</span><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m7.5 5 5 5-5 5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></a>
    </div>
  </header>
  <main class="portfolio-main">
    <section class="portfolio-hero" aria-labelledby="portfolio-title">
      <div><p class="eyebrow" data-i18n="eyebrow">همکاری‌های سازمانی منتخب</p><h1 id="portfolio-title"><span data-i18n="titleOutline">Portfolio</span><span data-i18n="title">اثر در مقیاس سازمانی</span></h1></div>
      <div><p class="hero-copy" data-i18n="intro">منتخبی از سازمان‌هایی که در پروژه‌های زیرساخت، امنیت، پشتیبان‌گیری، تحول دیجیتال و تداوم کسب‌وکار با آن‌ها همکاری داشته‌ام.</p><div class="hero-stats"><div class="hero-stat"><b>21</b><span data-i18n="statClients">سازمان منتخب</span></div><div class="hero-stat"><b>15+</b><span data-i18n="statYears">سال تجربه سازمانی</span></div></div></div>
    </section>
    <section class="clients" id="clients" aria-labelledby="clients-title">
      <header class="section-head"><h2 id="clients-title" data-i18n="clientsTitle">مورد اعتماد سازمان‌ها</h2><p data-i18n="clientsIntro">لوگوها با یک سیستم بصری یکپارچه نمایش داده می‌شوند؛ نام و هویت اصلی هر سازمان حفظ شده است.</p></header>
      <div class="client-grid">
        <article class="client-card" style="--brand:#2f8d73"><div class="client-logo"><span class="client-mark">ICC</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/iran-chamber.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/iran-chamber.webp" width="200" height="145" alt="Iran Chamber of Commerce, Industries, Mines and Agriculture" loading="eager" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="اتاق بازرگانی، صنایع، معادن و کشاورزی ایران">Iran Chamber of Commerce</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">01</i></article>
        <article class="client-card" style="--brand:#3aa64b"><div class="client-logo"><span class="client-mark">HT</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/haft-tappeh.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/haft-tappeh.webp" width="460" height="333" alt="Haft Tappeh Sugarcane Agro-Industry" loading="eager" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="کشت و صنعت نیشکر هفت‌تپه">Haft Tappeh Sugarcane</b><span data-i18n="infrastructure">Infrastructure & continuity</span></div><i class="client-index">02</i></article>
        <article class="client-card" style="--brand:#d77f2d"><div class="client-logo"><span class="client-mark">NIC</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/national-copper.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/national-copper.webp" width="460" height="333" alt="National Iranian Copper Industries Company" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="شرکت ملی صنایع مس ایران">National Iranian Copper Industries</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">03</i></article>
        <article class="client-card" style="--brand:#2778c4"><div class="client-logo"><span class="client-mark">IAU</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/azad-university.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/azad-university.webp" width="460" height="333" alt="Islamic Azad University" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="دانشگاه آزاد اسلامی">Islamic Azad University</b><span data-i18n="education">Education technology</span></div><i class="client-index">04</i></article>
        <article class="client-card" style="--brand:#e9b426"><div class="client-logo"><span class="client-mark">GE</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/golzar-ettesal.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/golzar-ettesal.webp" width="460" height="333" alt="Golzar Ettesal Trading Company" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="شرکت گلزار اتصال">Golzar Ettesal Trading Co.</b><span data-i18n="infrastructure">Infrastructure & continuity</span></div><i class="client-index">05</i></article>
        <article class="client-card" style="--brand:#465eb6"><div class="client-logo"><span class="client-mark">TCI</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/tci-khorasan.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/tci-khorasan.webp" width="460" height="333" alt="Telecommunication Company of Iran, Khorasan Razavi" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="مخابرات خراسان رضوی">TCI Khorasan Razavi</b><span data-i18n="backup">Backup & recovery</span></div><i class="client-index">06</i></article>
        <article class="client-card" style="--brand:#b79345"><div class="client-logo"><span class="client-mark">UAC</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/usul-al-deen.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/usul-al-deen.webp" width="460" height="333" alt="Usul Al Deen College" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="دانشکده اصول‌الدین">Usul Al Deen College</b><span data-i18n="education">Education technology</span></div><i class="client-index">07</i></article>
        <article class="client-card" style="--brand:#3baec2"><div class="client-logo"><span class="client-mark">HSA</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/hava-system-aria.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/hava-system-aria.webp" width="460" height="333" alt="Hava System Aria" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="هوا سیستم آریا">Hava System Aria</b><span data-i18n="infrastructure">Infrastructure & continuity</span></div><i class="client-index">08</i></article>
        <article class="client-card" style="--brand:#6b8d3a"><div class="client-logo"><span class="client-mark">DMJ</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/dmj.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/dmj.webp" width="460" height="333" alt="Darvazeh Melal Jahan Company" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="شرکت دروازه ملل جهان">Darvazeh Melal Jahan Co.</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">09</i></article>
        <article class="client-card" style="--brand:#7a5c9e"><div class="client-logo"><span class="client-mark">MD</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/modaberan.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/modaberan.webp" width="460" height="333" alt="Modaberan" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="مدابران">Modaberan</b><span data-i18n="education">Education technology</span></div><i class="client-index">10</i></article>
        <article class="client-card" style="--brand:#2a7a8c"><div class="client-logo"><span class="client-mark">DN</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/daryayenoorzeous.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/daryayenoorzeous.webp" width="460" height="333" alt="DaryayeNoorZeous" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="دریای نور زئوس">DaryayeNoorZeous</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">11</i></article>
        <article class="client-card" style="--brand:#c0504d"><div class="client-logo"><span class="client-mark">CQ</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/charity-qom.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/charity-qom.webp" width="460" height="333" alt="Charity in Qom" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="خیریه ایتام قم">Charity in Qom</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">12</i></article>
        <article class="client-card" style="--brand:#2f6db7"><div class="client-logo"><span class="client-mark">Noor</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/noor-eye-hospital.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/noor-eye-hospital.webp" width="200" height="200" alt="بیمارستان چشم پزشکی نور" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="بیمارستان چشم‌پزشکی نور">Noor Eye Hospital</b><span data-i18n="healthcare">Healthcare technology</span></div><i class="client-index">13</i></article>
        <article class="client-card" style="--brand:#2d7c9c"><div class="client-logo"><span class="client-mark">NASR</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/sazman-nasr.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/sazman-nasr.webp" width="150" height="150" alt="سازمان نظام صنفی رایانه‌ای کشور" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="سازمان نظام صنفی رایانه‌ای کشور">Iran Computer Systems &amp; IT Guild Organization</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">14</i></article>
        <article class="client-card" style="--brand:#7c4b9f"><div class="client-logo"><span class="client-mark">KHU</span><picture><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/kharazmi-university.webp" width="204" height="282" alt="دانشگاه خوارزمی" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="دانشگاه خوارزمی">Kharazmi University</b><span data-i18n="education">Education technology</span></div><i class="client-index">15</i></article>
        <article class="client-card" style="--brand:#d46b29"><div class="client-logo"><span class="client-mark">HP</span><picture><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/hamrahpeyda.webp" width="97" height="100" alt="فناوری همراه پیدا" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="فناوری همراه پیدا">Hamrah Peyda Technology</b><span data-i18n="backup">Backup &amp; recovery</span></div><i class="client-index">16</i></article>
        <article class="client-card" style="--brand:#c28e1f"><div class="client-logo"><span class="client-mark">MFT</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/tehran-fani-center.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/tehran-fani-center.webp" width="256" height="176" alt="مجتمع فنی تهران" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="مجتمع فنی تهران">Tehran Technical Complex</b><span data-i18n="education">Education technology</span></div><i class="client-index">17</i></article>
        <article class="client-card" style="--brand:#6b8e23"><div class="client-logo"><span class="client-mark">HRB</span><picture><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/hirbodan.webp" width="230" height="110" alt="مدیریت هیربدان" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="مدیریت هیربدان">Hirbodan Management</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">18</i></article>
        <article class="client-card" style="--brand:#1f6f8b"><div class="client-logo"><span class="client-mark">ALB</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/alborz-industrial-town.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/alborz-industrial-town.webp" width="280" height="80" alt="شهرک صنعتی استان البرز" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="شهرک صنعتی استان البرز">Alborz Industrial Town</b><span data-i18n="infrastructure">Infrastructure &amp; continuity</span></div><i class="client-index">19</i></article>
        <article class="client-card" style="--brand:#b8692c"><div class="client-logo"><span class="client-mark">AAA</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/aliazh-josh-ariya.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/aliazh-josh-ariya.webp" width="460" height="460" alt="آلیاژ جوش آریا" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="آلیاژ جوش آریا">Aliazh Josh Ariya</b><span data-i18n="enterprise">Enterprise engagement</span></div><i class="client-index">20</i></article>
        <article class="client-card" style="--brand:#0f5c7a"><div class="client-logo"><span class="client-mark">SOO</span><picture><source srcset="/<?php echo KDCV; ?>/assets/images/portfolio/logos/nisoc.avif" type="image/avif"><img src="<?php echo KDCV; ?>/assets/images/portfolio/logos/nisoc.webp" width="240" height="64" alt="مناطق نفت‌خیز جنوب" loading="lazy" decoding="async"></picture></div><div class="client-meta"><b data-org-fa="مناطق نفت‌خیز جنوب">South Oil Regions</b><span data-i18n="infrastructure">Infrastructure &amp; continuity</span></div><i class="client-index">21</i></article>
      </div>
    </section>
  </main>
  <footer class="portfolio-footer portfolio-main">
      <div class="kdcv-foot">
        <a class="kdcv-foot-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="Mohammad Ali Kohandezh">
          <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="36" height="36" alt="">
          <span>Mohammad Ali Kohandezh</span>
        </a>
        <nav class="kdcv-foot-nav" aria-label="Site">
          <a href="<?php echo esc_url( home_url('/blog/') ); ?>">Blog</a>
          <a href="<?php echo esc_url( home_url('/portfolio/') ); ?>">Portfolio</a>
          <a href="<?php echo esc_url( home_url('/certificates/') ); ?>">Certificates</a>
          <a href="<?php echo esc_url( home_url('/psn/') ); ?>">PSN Trophy Room</a>
          <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">Privacy Policy</a>
          <a href="<?php echo esc_url( home_url('/terms/') ); ?>">Terms of Use</a>
        </nav>
        <p class="kdcv-foot-legal">All rights reserved<br>© 2026 Mohammad Ali Kohandezh</p>
      </div></footer>
  <script src="<?php echo KDCV; ?>/assets/js/cybernetic-grid.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/portfolio.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/lazy-bundle.min.js?v=2026091705" defer></script>
  <?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><script src="<?php echo KDCV; ?>/assets/js/kohan-avatar.min.js?v=2026091705" defer></script><?php endif; ?>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar-enhance.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/chat-ui.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/hud-button.min.js?v=2026091705" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
