<?php /* KohandezhCV — privacy page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!DOCTYPE html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="privacy" data-kdcv-i18n-source="fa" lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="سیاست حریم خصوصی kohandezh.com — کوکی‌های عملکردی، حافظهٔ مرورگر، فرم‌ها و سرویس‌های شخص ثالث را شفاف توضیح می‌دهد؛ بدون ابزار تحلیل یا ردیابی تبلیغاتی.">
  <meta name="theme-color" content="#080b0d">
  <meta name="author" content="Mohammad Ali Kohandezh">
  <meta name="robots" content="index, follow">
  <title>سیاست حریم خصوصی | Privacy Policy — Kohandezh.com</title>
  <link rel="preload" href="<?php echo KDCV; ?>/assets/fonts/estedad/Estedad-VF.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/icomoon/style.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/blog.min.css?v=2026091705">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/flow-field-background.min.css?v=2026091705">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2026091701">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="<?php echo KDCV; ?>/assets/images/logo/apple-touch-icon.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="canonical" href="<?php echo esc_url( home_url('/privacy/') ); ?>">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@kohandezh">
  <meta name="twitter:title" content="سیاست حریم خصوصی | Privacy Policy — Kohandezh.com">
  <meta name="twitter:description" content="سیاست حریم خصوصی kohandezh.com — کوکی‌های عملکردی، حافظهٔ مرورگر، فرم‌ها و سرویس‌های شخص ثالث را شفاف توضیح می‌دهد؛ بدون ابزار تحلیل یا ردیابی تبلیغاتی.">
  <meta name="twitter:image" content="<?php echo KDCV; ?>/assets/images/avatar/avatar-professional.webp">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=2026091705">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/hud-button.min.css?v=2026091705">
  <?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=2026091705" media="print" onload="this.media='all'"><?php endif; ?><noscript><?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=2026091705"><?php endif; ?></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=2026091705" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=2026091705"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=2026091705" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=2026091705"></noscript>
  <!-- Breadcrumb trail: lets Google render the path instead of a bare
       URL in results, and gives answer engines the page's place in the
       site rather than treating it as an orphan. -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "خانه",
      "item": "https://kohandezh.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Privacy Policy",
      "item": "https://kohandezh.com/privacy/"
    }
  ]
}
  </script>
    <?php wp_head(); ?>
</head>
<body class="blog-page">
<?php wp_body_open(); ?>
<!-- WAITING:BEGIN generated from _tooling/waiting/waiting.partial.html by _tooling/waiting/build.py -- do not edit by hand -->
<style>
#kdcv-waiting{--kw-bg:#ebebeb;--kw-ink:#0a7233;--kw-trk:rgba(10,114,51,.14);position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;background:var(--kw-bg);animation:kdcvw-h .4s 6s forwards}
#kdcv-waiting.kdcv-waiting-dk,html[data-kdcv-theme=dark] #kdcv-waiting{--kw-bg:#0f0f0f;--kw-ink:#a8ff46;--kw-trk:rgba(240,255,222,.12)}
html[data-kdcv-theme=light] #kdcv-waiting{--kw-bg:#ebebeb;--kw-ink:#0a7233;--kw-trk:rgba(10,114,51,.14)}
.kdcv-waiting-out{opacity:0;visibility:hidden;pointer-events:none;transition:opacity .36s .26s,visibility 0s .62s}
.kdcv-waiting-r.kdcv-waiting-out{transition:opacity .2s,visibility 0s .2s}
#kdcv-waiting svg{width:clamp(96px,24vmin,132px);height:auto;overflow:visible}
.kdcvw-t{stroke:var(--kw-trk)}
.kdcvw-c,.kdcvw-f{stroke:var(--kw-ink)}
.kdcvw-c{stroke-dasharray:487 1542}
.kdcvw-f{stroke-dasharray:2029;stroke-dashoffset:2029;opacity:0}
.kdcv-waiting-out .kdcvw-c{opacity:0;transition:opacity .15s}
.kdcv-waiting-out .kdcvw-f{opacity:1;stroke-dashoffset:0;transition:stroke-dashoffset .36s cubic-bezier(.65,0,.35,1)}
@media (prefers-reduced-motion:no-preference){
#kdcv-waiting svg{animation:kdcvw-in .5s cubic-bezier(.2,.8,.2,1) both}
.kdcvw-c{animation:kdcvw-run 1.4s linear infinite}
.kdcvw-a{animation:kdcvw-p 2.8s ease-in-out infinite}
.kdcv-waiting-r svg{animation:none}
}
@media (prefers-reduced-motion:reduce){.kdcvw-c,.kdcvw-f{display:none}}
@keyframes kdcvw-h{from{pointer-events:none}to{opacity:0;visibility:hidden;pointer-events:none}}
@keyframes kdcvw-in{from{opacity:0;transform:scale(.9)}}
@keyframes kdcvw-run{to{stroke-dashoffset:-2029}}
@keyframes kdcvw-p{50%{opacity:.6}}
</style>
<noscript><style>#kdcv-waiting{display:none}</style></noscript>
<div id="kdcv-waiting" role="progressbar" aria-label="Loading"><svg viewBox="-40 -40 592 592" aria-hidden="true"><defs><linearGradient id="kdcvw-tile" x1="0" y1="0" x2="512" y2="512" gradientUnits="userSpaceOnUse"><stop stop-color="#171D1B"/><stop offset="1" stop-color="#050807"/></linearGradient><linearGradient id="kdcvw-accent" x1="200" y1="270" x2="255" y2="380" gradientUnits="userSpaceOnUse"><stop stop-color="#D9FF8A"/><stop offset="1" stop-color="#4FD35F"/></linearGradient></defs><g fill="none" stroke-width="12" stroke-linecap="round"><rect class="kdcvw-t" x="-28" y="-28" width="568" height="568" rx="142"/><rect class="kdcvw-c" x="-28" y="-28" width="568" height="568" rx="142"/><rect class="kdcvw-f" x="-28" y="-28" width="568" height="568" rx="142"/></g><rect width="512" height="512" rx="114" fill="url(#kdcvw-tile)"/><path class="kdcvw-a" d="M262 268 205 380 258 380 258 268Z" fill="url(#kdcvw-accent)"/><g fill="none" stroke="#F0FFDE" stroke-width="46" stroke-linecap="round" stroke-linejoin="round"><path d="M126 372V174l79 100 79-100v198"/><path d="M284 268 396 156M284 268l112 112"/></g></svg></div>
<script>(function(){var d=document,w=window,h=d.documentElement,e=d.getElementById("kdcv-waiting"),T=setTimeout,D=Date.now,t0=D(),ti,n,f,t,m,M,C;if(!e)return;
function k(){n=1;e.remove()}
function o(){n||(n=1,e.className+=" kdcv-waiting-out",T(k,f?680:260))}
function q(s){try{return matchMedia(s).matches}catch(x){}}
function a(y,z,p){w.addEventListener(y,z,p)}
if(/bot|crawl|spider|slurp|facebookexternalhit/i.test(navigator.userAgent)||d.readyState=="complete")return k();
try{t=sessionStorage;f=!t.getItem("kdcvWaitingSeen");t.setItem("kdcvWaitingSeen",1)}catch(x){}
try{t=h.getAttribute("data-kdcv-theme");if(!t){try{m=localStorage.getItem("darkMode")}catch(x){}t=m!=null?m=="enabled"?"dark":"light":d.body.dataset.defaultMode||(q("(prefers-color-scheme:dark)")?"dark":"light")}
e.className+=(t=="dark"?" kdcv-waiting-dk":"")+(f?"":" kdcv-waiting-r");
t={fa:"در حال بارگذاری",ar:"جارٍ التحميل",de:"Wird geladen",es:"Cargando",fr:"Chargement",tr:"Yükleniyor",zh:"加载中",ja:"読み込み中",ru:"Загрузка"}[h.lang.slice(0,2)];t&&e.setAttribute("aria-label",t)}catch(x){}
M=f&&!q("(prefers-reduced-motion:reduce)")?940:0;C=f?1200:0;
function g(){var z=D();z-t0<M||!(d.readyState=="complete"||ti&&z-ti>=C||z-t0>=3e3)||o()}
function i(){ti=ti||D();g();T(g,C)}
a("keydown",o,!0);a("pointerdown",o,!0);a("pageshow",function(v){v.persisted&&k()});
d.addEventListener("load",g,!0);d.readyState=="loading"?d.addEventListener("readystatechange",i):i();T(g,M);T(g,3e3)})()</script>
<!-- WAITING:END -->
<script>/* Theme boot — runs before paint so a page never flashes the wrong theme on navigation. Mirrors main.js: stored choice wins, then data-default-mode, then light. `light` is the class portfolio.js uses. */(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <div class="blog-shell">
    <header class="blog-header">
      <a class="blog-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="بازگشت به صفحه اصلی محمدعلی کهن‌دژ">
        <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="MK">
        <span>MOHAMMAD ALI KOHANDEZH</span>
      </a>
      <nav class="blog-nav" aria-label="ناوبری">
        <a href="<?php echo esc_url( home_url('/') ); ?>">صفحه اصلی</a>
        <a href="<?php echo esc_url( home_url('/blog/') ); ?>">وبلاگ</a>
        <a href="<?php echo esc_url( home_url('/terms/') ); ?>">شرایط استفاده</a>
      </nav>
      <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
        <div class="blog-header-actions">
      </div>
    </header>

    <main>
      <article class="blog-article">
        <header class="blog-article-header">
          <span class="blog-eyebrow" data-i18n="e01">حریم خصوصی</span>
          <h1 data-i18n="k01">سیاست حریم خصوصی</h1>
          <div class="blog-meta"><span data-i18n="m01">آخرین به‌روزرسانی: شهریور ۱۴۰۵</span><span data-i18n="m02">Privacy Policy</span></div>
        </header>

        <div class="blog-article-body">
          <aside class="blog-source-note" aria-label="خلاصه">
            <strong data-i18n="k32">خلاصهٔ کوتاه</strong>
            <p data-i18n="k02">این وب‌سایت از <strong>کوکی‌های عملکردی ضروری</strong> برای ترجیح زبان یا مدیریت نشست فنی استفاده می‌کند، اما از <strong>ابزار تحلیل، تبلیغات یا ردیابی رفتاری</strong> مانند Google Analytics یا Meta Pixel استفاده نمی‌کند. دادهٔ فرم فقط زمانی ارسال می‌شود که خودتان آن را ثبت کنید.</p>
          </aside>

          <h2 id="collect" data-i18n="k03">چه داده‌هایی جمع‌آوری می‌شود؟</h2>
          <p data-i18n="k04">فقط داده‌هایی که خودتان به‌صورت داوطلبانه وارد می‌کنید:</p>
          <ul>
            <li data-i18n="k05"><strong>فرم تماس و درخواست دمو:</strong> نام، نشانی ایمیل، شمارهٔ تماس، نام سازمان، حوزهٔ مورد علاقه و متن پیام شما.</li>
            <li data-i18n="k06"><strong>دستیار گفت‌وگوی هوش مصنوعی:</strong> اگر از ویجت گفت‌وگو استفاده کنید، متن پرسش شما برای تولید پاسخ پردازش می‌شود.</li>
          </ul>
          <p data-i18n="k07">هیچ اطلاعاتی دربارهٔ صفحاتی که بازدید می‌کنید، مدت حضور شما یا مسیر حرکت‌تان در سایت ثبت یا تحلیل نمی‌شود.</p>

          <h2 id="cookies" data-i18n="k08">کوکی‌ها و حافظهٔ مرورگر</h2>
          <p data-i18n="k09">سایت ممکن است کوکی‌های ضروری مانند <code>kdcv_lang</code> برای زبان انتخابی و یک شناسهٔ نشست فنی از سوی WordPress یا میزبان تنظیم کند. این کوکی‌ها برای تحلیل یا تبلیغات استفاده نمی‌شوند. ترجیحات نمایشی زیر نیز در <code>localStorage</code> مرورگر شما ذخیره می‌شوند و به‌طور خودکار به سرور ارسال نمی‌شوند:</p>
          <ul>
            <li data-i18n="k10"><code>darkMode</code> — حالت تیره یا روشن</li>
            <li data-i18n="k11"><code>siteLang</code> — زبان انتخابی شما</li>
            <li data-i18n="k12"><code>kohan-avatar-size-v1</code> و <code>kohan-avatar-classic-v1</code> — تنظیمات نمایش آواتار</li>
          </ul>
          <p data-i18n="k13">این موارد برای ردیابی یا تبلیغات به کار نمی‌روند. می‌توانید کوکی‌ها و داده‌های محلی را هر زمان از تنظیمات مرورگر پاک کنید؛ در این صورت ممکن است زبان یا ظاهر انتخابی شما بازنشانی شود.</p>

          <h2 id="third-party" data-i18n="k14">سرویس‌های شخص ثالث</h2>
          <p data-i18n="k15">برای شفافیت کامل، این سرویس‌های بیرونی در سایت استفاده می‌شوند:</p>
          <ul>
            <li data-i18n="k16"><strong>Web3Forms</strong> — ارسال فرم تماس. محتوای فرم شما از طریق این سرویس به ایمیل ما تحویل داده می‌شود.</li>
            <li data-i18n="k17"><strong>آپارات (Aparat)</strong> — نمایش ویدئوهای مصاحبه در برخی نوشته‌های وبلاگ. ویدئو در قاب آپارات بارگذاری می‌شود و ممکن است آپارات سیاست‌های خودش را اعمال کند.</li>
            <li data-i18n="k18"><strong>دکمه‌های هم‌رسانی</strong> — لینک به لینکدین، ایکس، تلگرام و واتساپ. این‌ها فقط پیوند ساده‌اند و تا زمانی که روی آن‌ها کلیک نکنید هیچ داده‌ای ارسال نمی‌کنند.</li>
            <li data-i18n="k19"><strong>سرویس مدل زبانی</strong> — در صورت فعال‌بودن دستیار گفت‌وگو، پرسش شما برای تولید پاسخ به ارائه‌دهندهٔ مدل ارسال می‌شود.</li>
          </ul>
          <p data-i18n="k20">هر یک از این سرویس‌ها سیاست حریم خصوصی مستقل خود را دارند.</p>

          <h2 id="use" data-i18n="k21">داده‌ها چگونه استفاده می‌شوند؟</h2>
          <p data-i18n="k22">تنها برای پاسخ‌دادن به پیام شما و پیگیری همان درخواست. داده‌های شما فروخته نمی‌شوند، اجاره داده نمی‌شوند و برای تبلیغات یا فهرست ایمیل انبوه استفاده نمی‌شوند.</p>

          <h2 id="rights" data-i18n="k23">حقوق شما</h2>
          <p data-i18n="k24">می‌توانید درخواست کنید که پیام‌های ارسالی‌تان حذف شوند، بخواهید بدانید چه اطلاعاتی از شما نگهداری می‌شود، یا اصلاح آن را بخواهید. کافی است از طریق <a href="<?php echo esc_url( home_url('/') ); ?>#contact">صفحهٔ تماس</a> اطلاع دهید.</p>

          <h2 id="security" data-i18n="k25">امنیت</h2>
          <p data-i18n="k26">سایت روی HTTPS ارائه می‌شود و هدرهای امنیتی استاندارد روی آن فعال است. با این حال هیچ سامانه‌ای صددرصد ایمن نیست؛ لطفاً اطلاعات حساس (مانند رمز عبور، شمارهٔ کارت بانکی یا مدارک هویتی) را از طریق فرم تماس ارسال نکنید.</p>

          <h2 id="changes" data-i18n="k27">تغییرات این سیاست</h2>
          <p data-i18n="k28">در صورت تغییر، تاریخ «آخرین به‌روزرسانی» در بالای همین صفحه اصلاح می‌شود.</p>

          <hr data-kdcv-i18n-drop>

          <h2 id="en" lang="en" dir="ltr" data-kdcv-i18n-drop data-i18n="k29">Privacy Policy (English summary)</h2>
          <div lang="en" dir="ltr" data-kdcv-i18n-drop>
            <p data-i18n="k30"><strong>This site may set essential first-party cookies, but uses no analytics, advertising or behavioural-tracking tools.</strong> Functional cookies can remember a language choice or support a technical session.</p>
            <p data-i18n="k31"><strong>What is collected:</strong> only what you type into the contact/demo form (name, email, phone, company, area of interest, message), and your question if you use the AI chat widget.</p>
            <p data-i18n="k32"><strong>Cookies and browser storage:</strong> essential first-party cookies may remember language or support a technical session. Functional <code>localStorage</code> keys hold theme, language and avatar preferences on your device. None of these are used for analytics or advertising.</p>
            <p data-i18n="k33"><strong>Third parties:</strong> Web3Forms (form delivery), Aparat (embedded interview videos), social share links (only on click), and a language-model provider if the chat assistant is enabled. Each has its own privacy policy.</p>
            <p data-i18n="k34"><strong>Your rights:</strong> you may ask what is held about you, request corrections, or request deletion — just <a href="<?php echo esc_url( home_url('/') ); ?>#contact">get in touch</a>.</p>
            <p data-i18n="k35">Please do not send passwords, card numbers or identity documents through the contact form.</p>
          </div>
        </div>

        <footer class="blog-article-footer">

          <a class="blog-read" href="<?php echo esc_url( home_url('/terms/') ); ?>">شرایط استفاده <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
          <a class="blog-read" href="<?php echo esc_url( home_url('/') ); ?>">بازگشت به صفحه اصلی <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
        </footer>
      </article>
    </main>

    <footer class="blog-footer">
      <div class="kdcv-foot">
        <a class="kdcv-foot-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="Mohammad Ali Kohandezh">
          <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="36" height="36" alt="">
          <span>Mohammad Ali Kohandezh</span>
        </a>
        <nav class="kdcv-foot-nav" aria-label="Site">
          <a href="<?php echo esc_url( home_url('/blog/') ); ?>">Blog</a>
          <a href="<?php echo esc_url( home_url('/portfolio/') ); ?>">Portfolio</a>
          <a href="<?php echo esc_url( home_url('/certificates/') ); ?>">Certificates</a>
          <a href="<?php echo esc_url( home_url('/psn/') ); ?>">PSN Trophy Room</a>
          <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">Privacy Policy</a>
          <a href="<?php echo esc_url( home_url('/terms/') ); ?>">Terms of Use</a>
        </nav>
        <p class="kdcv-foot-legal">All rights reserved<br>© 2026 Mohammad Ali Kohandezh</p>
      </div>
    </footer>
  </div>
  <script src="<?php echo KDCV; ?>/assets/js/pwa-register.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/flow-field-background.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/lazy-bundle.min.js?v=2026091705" defer></script>
  <?php if ( ! class_exists('Kohan_Avatar') || empty(Kohan_Avatar::instance()->get_options()['enabled']) ) : ?><script src="<?php echo KDCV; ?>/assets/js/kohan-avatar.min.js?v=2026091705" defer></script><?php endif; ?>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar-enhance.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-drive.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/chat-ui.min.js?v=2026091705" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/hud-button.min.js?v=2026091705" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
