<?php /* KohandezhCV — privacy page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!DOCTYPE html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="privacy" data-kdcv-i18n-source="fa" lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="سیاست حریم خصوصی kohandezh.com — این وب‌سایت از کوکی، ابزار تحلیلی یا ردیابی استفاده نمی‌کند. توضیح دقیق داده‌هایی که جمع‌آوری می‌شوند.">
  <meta name="theme-color" content="#080b0d">
  <meta name="author" content="Mohammad Ali Kohandezh">
  <meta name="robots" content="index, follow">
  <title>سیاست حریم خصوصی | Privacy Policy — Kohandezh.com</title>
  <link rel="preload" href="<?php echo KDCV; ?>/assets/fonts/estedad/Estedad-VF.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/icomoon/style.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/blog.min.css?v=105">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/flow-field-background.min.css?v=95">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="<?php echo KDCV; ?>/assets/images/logo/apple-touch-icon.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="canonical" href="https://kohandezh.com/privacy/">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@kohandezh">
  <meta name="twitter:title" content="سیاست حریم خصوصی | Privacy Policy — Kohandezh.com">
  <meta name="twitter:description" content="سیاست حریم خصوصی kohandezh.com — این وب‌سایت از کوکی، ابزار تحلیلی یا ردیابی استفاده نمی‌کند. توضیح دقیق داده‌هایی که جمع‌آوری می‌شوند.">
  <meta name="twitter:image" content="<?php echo KDCV; ?>/assets/images/avatar/avatar-professional.webp">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=99">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/hud-button.min.css?v=103">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=123" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=123"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=2" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=2"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=107" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=107"></noscript>
  <!-- Breadcrumb trail: lets Google render the path instead of a bare
       URL in results, and gives answer engines the page's place in the
       site rather than treating it as an orphan. -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "خانه",
      "item": "https://kohandezh.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Privacy Policy",
      "item": "https://kohandezh.com/privacy/"
    }
  ]
}
  </script>
    <?php wp_head(); ?>
</head>
<body class="blog-page">
<?php wp_body_open(); ?>
<script>/* Theme boot — runs before paint so a page never flashes the wrong theme on navigation. Mirrors main.js: stored choice wins, then data-default-mode, then light. `light` is the class portfolio.js uses. */(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <div class="blog-shell">
    <header class="blog-header">
      <a class="blog-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="بازگشت به صفحه اصلی محمدعلی کهن‌دژ">
        <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="MK">
        <span>MOHAMMAD ALI KOHANDEZH</span>
      </a>
      <nav class="blog-nav" aria-label="ناوبری">
        <a href="<?php echo esc_url( home_url('/') ); ?>">صفحه اصلی</a>
        <a href="blog/index.html">وبلاگ</a>
        <a href="<?php echo esc_url( home_url('/terms/') ); ?>">شرایط استفاده</a>
      </nav>
      <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
        <div class="blog-header-actions">
      </div>
    </header>

    <main>
      <article class="blog-article">
        <header class="blog-article-header">
          <span class="blog-eyebrow" data-i18n="e01">حریم خصوصی</span>
          <h1 data-i18n="k01">سیاست حریم خصوصی</h1>
          <div class="blog-meta"><span data-i18n="m01">آخرین به‌روزرسانی: مرداد ۱۴۰۵</span><span data-i18n="m02">Privacy Policy</span></div>
        </header>

        <div class="blog-article-body">
          <aside class="blog-source-note" aria-label="خلاصه">
            <strong data-i18n="k32">خلاصهٔ کوتاه</strong>
            <p data-i18n="k02">این وب‌سایت <strong>هیچ کوکی‌ای تنظیم نمی‌کند</strong>، از <strong>هیچ ابزار تحلیلی یا ردیابی</strong> (مانند Google Analytics، Meta Pixel یا مشابه) استفاده نمی‌کند و رفتار شما را دنبال نمی‌کند. تنها زمانی داده‌ای از شما ذخیره می‌شود که خودتان فرم تماس را پر کنید.</p>
          </aside>

          <h2 id="collect" data-i18n="k03">چه داده‌هایی جمع‌آوری می‌شود؟</h2>
          <p data-i18n="k04">فقط داده‌هایی که خودتان به‌صورت داوطلبانه وارد می‌کنید:</p>
          <ul>
            <li data-i18n="k05"><strong>فرم تماس و درخواست دمو:</strong> نام، نشانی ایمیل، شمارهٔ تماس، نام سازمان، حوزهٔ مورد علاقه و متن پیام شما.</li>
            <li data-i18n="k06"><strong>دستیار گفت‌وگوی هوش مصنوعی:</strong> اگر از ویجت گفت‌وگو استفاده کنید، متن پرسش شما برای تولید پاسخ پردازش می‌شود.</li>
          </ul>
          <p data-i18n="k07">هیچ اطلاعاتی دربارهٔ صفحاتی که بازدید می‌کنید، مدت حضور شما یا مسیر حرکت‌تان در سایت ثبت یا تحلیل نمی‌شود.</p>

          <h2 id="cookies" data-i18n="k08">کوکی‌ها و حافظهٔ مرورگر</h2>
          <p data-i18n="k09">این سایت کوکی تنظیم نمی‌کند. برای اینکه تنظیمات شما بین بازدیدها حفظ شود، از <code>localStorage</code> مرورگر خودتان استفاده می‌شود. این داده‌ها روی دستگاه شما می‌مانند و هرگز به سرور ارسال نمی‌شوند:</p>
          <ul>
            <li data-i18n="k10"><code>darkMode</code> — حالت تیره یا روشن</li>
            <li data-i18n="k11"><code>siteLang</code> — زبان انتخابی شما</li>
            <li data-i18n="k12"><code>kohan-avatar-size-v1</code> و <code>kohan-avatar-classic-v1</code> — تنظیمات نمایش آواتار</li>
          </ul>
          <p data-i18n="k13">چون هیچ‌کدام از این موارد برای ردیابی یا تبلیغات به کار نمی‌روند و همگی برای عملکرد سایت ضروری‌اند، نمایش «بنر پذیرش کوکی» لازم نیست. می‌توانید هر زمان این داده‌ها را از تنظیمات مرورگر خود پاک کنید.</p>

          <h2 id="third-party" data-i18n="k14">سرویس‌های شخص ثالث</h2>
          <p data-i18n="k15">برای شفافیت کامل، این سرویس‌های بیرونی در سایت استفاده می‌شوند:</p>
          <ul>
            <li data-i18n="k16"><strong>Web3Forms</strong> — ارسال فرم تماس. محتوای فرم شما از طریق این سرویس به ایمیل ما تحویل داده می‌شود.</li>
            <li data-i18n="k17"><strong>آپارات (Aparat)</strong> — نمایش ویدئوهای مصاحبه در برخی نوشته‌های وبلاگ. ویدئو در قاب آپارات بارگذاری می‌شود و ممکن است آپارات سیاست‌های خودش را اعمال کند.</li>
            <li data-i18n="k18"><strong>دکمه‌های هم‌رسانی</strong> — لینک به لینکدین، ایکس، تلگرام و واتساپ. این‌ها فقط پیوند ساده‌اند و تا زمانی که روی آن‌ها کلیک نکنید هیچ داده‌ای ارسال نمی‌کنند.</li>
            <li data-i18n="k19"><strong>سرویس مدل زبانی</strong> — در صورت فعال‌بودن دستیار گفت‌وگو، پرسش شما برای تولید پاسخ به ارائه‌دهندهٔ مدل ارسال می‌شود.</li>
          </ul>
          <p data-i18n="k20">هر یک از این سرویس‌ها سیاست حریم خصوصی مستقل خود را دارند.</p>

          <h2 id="use" data-i18n="k21">داده‌ها چگونه استفاده می‌شوند؟</h2>
          <p data-i18n="k22">تنها برای پاسخ‌دادن به پیام شما و پیگیری همان درخواست. داده‌های شما فروخته نمی‌شوند، اجاره داده نمی‌شوند و برای تبلیغات یا فهرست ایمیل انبوه استفاده نمی‌شوند.</p>

          <h2 id="rights" data-i18n="k23">حقوق شما</h2>
          <p data-i18n="k24">می‌توانید درخواست کنید که پیام‌های ارسالی‌تان حذف شوند، بخواهید بدانید چه اطلاعاتی از شما نگهداری می‌شود، یا اصلاح آن را بخواهید. کافی است از طریق <a href="index.html#contact">صفحهٔ تماس</a> اطلاع دهید.</p>

          <h2 id="security" data-i18n="k25">امنیت</h2>
          <p data-i18n="k26">سایت روی HTTPS ارائه می‌شود و هدرهای امنیتی استاندارد روی آن فعال است. با این حال هیچ سامانه‌ای صددرصد ایمن نیست؛ لطفاً اطلاعات حساس (مانند رمز عبور، شمارهٔ کارت بانکی یا مدارک هویتی) را از طریق فرم تماس ارسال نکنید.</p>

          <h2 id="changes" data-i18n="k27">تغییرات این سیاست</h2>
          <p data-i18n="k28">در صورت تغییر، تاریخ «آخرین به‌روزرسانی» در بالای همین صفحه اصلاح می‌شود.</p>

          <hr data-kdcv-i18n-drop>

          <h2 id="en" lang="en" dir="ltr" data-kdcv-i18n-drop data-i18n="k29">Privacy Policy (English summary)</h2>
          <div lang="en" dir="ltr" data-kdcv-i18n-drop>
            <p data-i18n="k30"><strong>This site sets no cookies and uses no analytics or tracking tools</strong> — no Google Analytics, no advertising pixels, no behavioural profiling.</p>
            <p data-i18n="k31"><strong>What is collected:</strong> only what you type into the contact/demo form (name, email, phone, company, area of interest, message), and your question if you use the AI chat widget.</p>
            <p data-i18n="k32"><strong>Browser storage:</strong> four functional <code>localStorage</code> keys hold your theme, language and avatar preferences. They stay on your device and are never transmitted. Because none of them are used for tracking, no cookie-consent banner is required.</p>
            <p data-i18n="k33"><strong>Third parties:</strong> Web3Forms (form delivery), Aparat (embedded interview videos), social share links (only on click), and a language-model provider if the chat assistant is enabled. Each has its own privacy policy.</p>
            <p data-i18n="k34"><strong>Your rights:</strong> you may ask what is held about you, request corrections, or request deletion — just <a href="index.html#contact">get in touch</a>.</p>
            <p data-i18n="k35">Please do not send passwords, card numbers or identity documents through the contact form.</p>
          </div>
        </div>

        <footer class="blog-article-footer">

          <a class="blog-read" href="<?php echo esc_url( home_url('/terms/') ); ?>">شرایط استفاده <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
          <a class="blog-read" href="<?php echo esc_url( home_url('/') ); ?>">بازگشت به صفحه اصلی <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
        </footer>
      </article>
    </main>

    <footer class="blog-footer">
      <div class="kdcv-foot">
        <a class="kdcv-foot-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="Mohammad Ali Kohandezh">
          <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="36" height="36" alt="">
          <span>Mohammad Ali Kohandezh</span>
        </a>
        <nav class="kdcv-foot-nav" aria-label="Site">
          <a href="blog/index.html">Blog</a>
          <a href="<?php echo esc_url( home_url('/portfolio/') ); ?>">Portfolio</a>
          <a href="<?php echo esc_url( home_url('/certificates/') ); ?>">Certificates</a>
          <a href="<?php echo esc_url( home_url('/psn/') ); ?>">PSN Trophy Room</a>
          <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">Privacy Policy</a>
          <a href="<?php echo esc_url( home_url('/terms/') ); ?>">Terms of Use</a>
        </nav>
        <p class="kdcv-foot-legal">All rights reserved<br>© 2026 Mohammad Ali Kohandezh</p>
      </div>
    </footer>
  </div>
  <script src="<?php echo KDCV; ?>/assets/js/pwa-register.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/flow-field-background.min.js?v=95" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=107" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/lazy-bundle.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar.min.js?v=126" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar-enhance.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-drive.min.js?v=2" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=15" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=95" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/chat-ui.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/hud-button.min.js?v=102" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
