<?php /* KohandezhCV — knowledge page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!doctype html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="knowledge" data-kdcv-i18n-source="en" lang="en" dir="ltr" data-kdcv-router-mode="wordpress" data-kdcv-site-base="<?php echo esc_url(home_url('/')); ?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A practitioner's learning guide to AI and quantum readiness — curated stages, resources and field notes by Mohammad Ali Kohandezh.">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <meta name="theme-color" content="#080b0d">
  <title>Knowledge Hub — Learning AI &amp; Quantum | Mohammad Ali Kohandezh</title>
  <link rel="preload" href="<?php echo KDCV; ?>/assets/fonts/estedad/Estedad-VF.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/icomoon/style.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/simple-line/simple-line.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/blog.min.css?v=99">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=97">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2">
  <link rel="canonical" href="https://kohandezh.com/knowledge/">
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "name": "Knowledge Hub — Learning AI & Quantum",
    "url": "https://kohandezh.com/knowledge/",
    "author": { "@type": "Person", "@id": "https://kohandezh.com/#person", "name": "Mohammad Ali Kohandezh" },
    "hasPart": [
      { "@type": "LearningResource", "name": "AI learning track", "learningResourceType": "Learning path", "educationalLevel": "Beginner to practitioner", "teaches": "Applied artificial intelligence for professionals and organizations" },
      { "@type": "LearningResource", "name": "Quantum readiness track", "learningResourceType": "Learning path", "educationalLevel": "Beginner to practitioner", "teaches": "Quantum computing awareness and post-quantum security readiness" }
    ]
  }
  </script>
    <?php wp_head(); ?>
</head>
<body class="blog-page">
<?php wp_body_open(); ?>
<script>(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <div class="blog-shell">
    <header class="blog-header">
      <a class="blog-brand" href="<?php echo esc_url( home_url('/') ); ?>" data-i18n-aria="a_home" aria-label="Back to Mohammad Ali Kohandezh's home page">
        <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="MK">
        <span>MOHAMMAD ALI KOHANDEZH</span>
      </a>
      <nav class="blog-nav" data-i18n-aria="a_nav" aria-label="Knowledge hub navigation">
        <a href="blog/index.html" data-i18n="k01">All posts</a>
      </nav>
      <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
      <div class="blog-header-actions">
        <a href="index.html#contact" data-i18n-aria="a_chat" aria-label="Start a conversation" data-i18n="k02"><i class="icon icon-send"></i><span>Start a conversation</span></a>
      </div>
    </header>

    <main>
      <article class="blog-article">
        <header class="blog-article-header">
          <span class="blog-eyebrow" data-i18n="k03">Public knowledge</span>
          <h1 data-i18n="k04">Learning AI &amp; Quantum: a practitioner's map</h1>
          <div class="blog-meta"><span data-i18n="k05">Curated learning paths</span><span data-i18n="k06">Updated regularly</span></div>
        </header>

        <div class="blog-article-body">
          <p data-i18n="k07">Everything on this page comes from one conviction: technology creates value only when people can actually use it. These are the stages I recommend to colleagues, clients and students — not a course catalogue, but the shortest honest route from curiosity to competence, with my own field notes at each step.</p>

          <h2 id="ai-track" data-i18n="k08">Track 1 — Artificial intelligence</h2>

          <h3 data-i18n="k10">Stage 1 · Foundations: from spreadsheets to prompts</h3>
          <p data-i18n="k11">Before any theory, learn to hold a useful conversation with a modern model. Practise asking for drafts, summaries and comparisons in your own daily work for two weeks. The goal is not technical knowledge — it is losing the fear, and discovering where the tools genuinely save you time and where they confidently mislead you.</p>
          <p class="blog-source-note" data-i18n="k12"><strong>Field note:</strong> in our programmes at Kohan System Farda, the people who advance fastest are rarely the most technical — they are the ones who kept a daily log of what worked and what failed.</p>

          <h3 data-i18n="k13">Stage 2 · Core concepts: how the machine actually thinks</h3>
          <p data-i18n="k14">Learn what a language model really does: tokens, context windows, training versus inference, and why models hallucinate. Then study retrieval-augmented generation (RAG) — the pattern behind almost every serious enterprise assistant, including the one on this website. One good survey paper and one hands-on tutorial beat ten opinion videos.</p>

          <h3 data-i18n="k15">Stage 3 · Enterprise practice: agents, safety and value</h3>
          <p data-i18n="k16">The frontier is agentic AI: systems that plan, call tools and complete work. Study one real platform end-to-end — how it authenticates, what it is allowed to touch, how failures are contained. This is where AI meets security engineering, and it is exactly the intersection where the Padyar and HomaYar products live: an agent is only as trustworthy as the infrastructure underneath it.</p>

          <h2 id="quantum-track" data-i18n="k17">Track 2 — Quantum</h2>

          <h3 data-i18n="k19">Stage 1 · What quantum computing really is</h3>
          <p data-i18n="k20">Skip the popular-science mystique. A quantum computer is a machine that solves a narrow class of problems — factoring, search, simulation — dramatically faster than classical machines. Learn the honest state of the hardware: what qubit counts mean, why error correction is the real bottleneck, and why the useful timeline is measured in years, not decades.</p>

          <h3 data-i18n="k21">Stage 2 · The security consequence: harvest now, decrypt later</h3>
          <p data-i18n="k22">The reason a security professional cannot ignore quantum: encrypted data stolen today can be stored and decrypted once the hardware matures. Learn which algorithms fall (RSA, classical Diffie-Hellman, elliptic curves) and which survive. This threat model — not the physics — is what boards and CIOs need explained to them.</p>
          <p class="blog-source-note" data-i18n="k23"><strong>Field note:</strong> when I audit infrastructure, I now ask one added question: how long must this data stay secret? Anything sensitive beyond 2030 already deserves a post-quantum plan.</p>

          <h3 data-i18n="k24">Stage 3 · Post-quantum readiness in practice</h3>
          <p data-i18n="k25">NIST has already standardized post-quantum algorithms — ML-KEM for key exchange, ML-DSA for signatures. Practical readiness means three steps: inventory where cryptography lives in your organization, demand migration roadmaps from your vendors, and design new systems crypto-agile so an algorithm can be replaced without rebuilding the product.</p>

          <h2 data-i18n="k26">How to use this page</h2>
          <p data-i18n="k27">Pick one track and one stage. Spend two focused weeks on it before moving on. If you want to discuss a stage, a resource, or your organization's readiness — the assistant on this site answers in your language, and the contact form reaches me directly.</p>
        </div>

        <footer class="blog-article-footer">
          <a class="blog-read" href="blog/index.html" data-i18n="k28">All posts <i class="icon icon-arrow-right-top"></i></a>
          <a class="blog-read" href="index.html#contact" data-i18n="k29">Start a conversation <i class="icon icon-arrow-right-top"></i></a>
        </footer>
      </article>
    </main>

    <footer class="blog-footer"></footer>
  </div>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=5" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=5" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=5" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=5" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
