<?php /* KohandezhCV — psn page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!DOCTYPE html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="psn" data-kdcv-i18n-source="en" lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kohandezh PSN Trophy Room | PlayStation Achievements</title>
    <meta name="description" content="A focused snapshot of Mohammad Ali Kohandezh's PlayStation Network level, trophy collection, games and completion progress.">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
    <meta name="author" content="Mohammad Ali Kohandezh">
    <meta name="theme-color" content="#0f0f0f">
    <link rel="canonical" href="https://kohandezh.com/psn/">

    <meta property="og:type" content="profile">
    <meta property="og:title" content="Kohandezh PSN Trophy Room">
    <meta property="og:description" content="PlayStation level, trophy cabinet and progress snapshot for Kohandezh.">
    <meta property="og:url" content="https://kohandezh.com/psn/">
    <meta property="og:image" content="<?php echo KDCV; ?>/assets/images/psn-kohandezh-card.png">

    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Kohandezh PSN Trophy Room">
    <meta name="twitter:description" content="PlayStation level, trophy cabinet and progress snapshot for Kohandezh.">
    <meta name="twitter:image" content="<?php echo KDCV; ?>/assets/images/psn-kohandezh-card.png">

    <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="<?php echo KDCV; ?>/assets/images/logo/apple-touch-icon.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo KDCV; ?>/assets/images/logo/favicon-16.png?v=2">
    <link rel="icon" type="image/png" sizes="192x192" href="<?php echo KDCV; ?>/assets/images/logo/favicon-192.png?v=2">
    <link rel="apple-touch-icon" sizes="180x180" href="<?php echo KDCV; ?>/assets/images/logo/apple-touch-icon.png?v=2">

    <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/fonts.css">
    <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/psn.min.css?v=87">
    <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/flow-field-background.min.css?v=95">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=99">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/hud-button.min.css?v=103">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=125" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=125"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=3" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=3"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/wisdom-quotes.min.css?v=113" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/wisdom-quotes.min.css?v=113"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=108" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=108"></noscript>
  <!-- Breadcrumb trail: lets Google render the path instead of a bare
       URL in results, and gives answer engines the page's place in the
       site rather than treating it as an orphan. -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://kohandezh.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "PSN Trophy Room",
      "item": "https://kohandezh.com/psn/"
    }
  ]
}
  </script>
    <?php wp_head(); ?>
</head>
<body class="psn-page">
<?php wp_body_open(); ?>
<script>/* Theme boot — runs before paint so a page never flashes the wrong theme on navigation. Mirrors main.js: stored choice wins, then data-default-mode, then light. `light` is the class portfolio.js uses. */(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
    <a class="psn-skip-link" href="#main-content">Skip to content</a>

    <div class="psn-shell">
        <header class="psn-topbar">
            <a class="psn-brand" href="<?php echo esc_url( home_url('/') ); ?>" data-back-link aria-label="Back to the Kohandezh portfolio">
                <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="">
                <span class="psn-brand-copy">
                    <span class="psn-brand-name">KOHANDEZH</span>
                    <span class="psn-brand-context">Personal portfolio</span>
                </span>
            </a>

            <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
            <nav class="psn-top-actions" aria-label="Page actions">
                <a class="psn-top-link" href="<?php echo esc_url( home_url('/') ); ?>" data-back-link>
                    <svg viewBox="0 0 20 20" fill="none" aria-hidden="true">
                        <path d="M12.75 4.75 7.5 10l5.25 5.25" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span>Back to portfolio</span>
                </a>
                <a class="psn-top-link" href="https://psnprofiles.com/Kohandezh/" target="_blank" rel="noopener noreferrer">
                    PSNProfiles
                    <svg viewBox="0 0 20 20" fill="none" aria-hidden="true">
                        <path d="M7 13 13 7M8.25 7H13v4.75" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </a>
            </nav>
        </header>

        <main id="main-content">
            <section class="psn-hero" aria-labelledby="psn-title">
                <div class="psn-hero-copy">
                    <div class="psn-eyebrow">
                        <img src="<?php echo KDCV; ?>/assets/images/item/playstation.svg" width="20" height="20" alt="" aria-hidden="true">
                        PlayStation Network
                    </div>

                    <h1 class="psn-title" id="psn-title" data-i18n="k01">
                        Kohandezh
                        <span>Trophy Room</span>
                    </h1>

                    <p class="psn-lead" data-i18n="k02">
                        A concise record of games played, trophy milestones and completion progress — kept separate from the professional portfolio, but built with the same attention to detail.
                    </p>

                    <div class="psn-actions">
                        <a class="psn-button psn-button--primary" href="https://psnprofiles.com/Kohandezh/" target="_blank" rel="noopener noreferrer">
                            View on PSNProfiles
                            <svg viewBox="0 0 20 20" fill="none" aria-hidden="true">
                                <path d="M7 13 13 7M8.25 7H13v4.75" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </a>
                        <a class="psn-button psn-button--secondary" href="#trophy-cabinet">
                            Explore trophy cabinet
                        </a>
                    </div>

                    <p class="psn-snapshot-note" data-i18n="k03">
                        <span class="psn-snapshot-dot" aria-hidden="true"></span>
                        Profile snapshot recorded <time datetime="2026-07-09" data-snapshot-date>July 9, 2026</time>
                    </p>
                </div>

                <aside class="psn-profile-card psn-profile-card--photo" aria-label="Kohandezh PlayStation profile snapshot">
                    <!-- The portrait is the card, not a thumbnail inside it: it fills the
                         whole outer frame and every other element sits on top of it.
                         A scrim (see .psn-profile-card--photo::before) keeps the copy
                         legible over whatever part of the image it lands on. -->
                    <picture class="psn-profile-photo">
                        <source srcset="<?php echo KDCV; ?>/assets/images/avatar/kohandezhpsn.webp" type="image/webp">
                        <img src="<?php echo KDCV; ?>/assets/images/avatar/kohandezhpsn.webp" width="512" height="768" alt="Mohammad Ali Kohandezh — PlayStation Network profile picture" loading="lazy" decoding="async">
                    </picture>
                    <div class="psn-profile-head">
                        <!-- The portrait used to float in the hero copy, where it read as a
                             stray illustration. It belongs to this card: it IS the profile
                             picture for the handle beside it. The PlayStation mark rides
                             along as a corner badge, the way PSN shows a platform badge. -->
                        <span class="psn-profile-mark" aria-hidden="true">
                            <img src="<?php echo KDCV; ?>/assets/images/item/playstation.svg" width="18" height="18" alt="">
                        </span>
                        <div>
                            <h2 class="psn-handle" data-i18n="k04">Kohandezh</h2>
                            <span class="psn-profile-label">PlayStation trophy profile</span>
                        </div>
                    </div>

                    <div class="psn-profile-level">
                        <div class="psn-level-copy">
                            <span class="psn-level-label">PSN level</span>
                            <strong class="psn-level-value" data-stat="level">261</strong>
                        </div>
                        <span class="psn-level-badge">Snapshot data</span>
                    </div>

                    <picture><source srcset="<?php echo KDCV; ?>/assets/images/psn-kohandezh-card.avif" type="image/avif"><img class="psn-card-image" src="<?php echo KDCV; ?>/assets/images/psn-kohandezh-card.webp" width="405" height="120" alt=""></picture>

                    <div class="psn-profile-meta">
                        <span>Public profile-card snapshot</span>
                        <span>Source: PSNProfiles</span>
                    </div>
                </aside>
            </section>

            <section class="psn-section" id="profile-overview" aria-labelledby="overview-title">
                <header class="psn-section-head">
                    <span class="psn-section-index" aria-hidden="true">01</span>
                    <div>
                        <h2 class="psn-section-title" id="overview-title" data-i18n="k05">Profile snapshot</h2>
                        <p class="psn-section-copy" data-i18n="k06">The core profile metrics captured from the public PSNProfiles card. Values are presented as a dated snapshot, not as a live feed.</p>
                    </div>
                </header>

                <dl class="psn-stats">
                    <div class="psn-stat">
                        <dt data-i18n="k07">PSN level</dt>
                        <dd data-stat="level" data-i18n="k08">261</dd>
                    </div>
                    <div class="psn-stat">
                        <dt data-i18n="k09">Total trophies</dt>
                        <dd data-stat="total" data-i18n="k10">1,975</dd>
                    </div>
                    <div class="psn-stat">
                        <dt data-i18n="k11">Games played</dt>
                        <dd data-stat="games" data-i18n="k12">371</dd>
                    </div>
                    <div class="psn-stat">
                        <dt data-i18n="k13">Completion</dt>
                        <dd data-stat="completion" data-i18n="k14">15.7%</dd>
                    </div>
                    <div class="psn-stat">
                        <dt data-i18n="k15">Trophy points</dt>
                        <dd data-stat="points" data-i18n="k16">42,705</dd>
                    </div>
                </dl>
            </section>

            <section class="psn-section" id="trophy-cabinet" aria-labelledby="cabinet-title">
                <header class="psn-section-head">
                    <span class="psn-section-index" aria-hidden="true">02</span>
                    <div>
                        <h2 class="psn-section-title" id="cabinet-title" data-i18n="k17">Trophy cabinet</h2>
                        <p class="psn-section-copy" data-i18n="k18">A simple breakdown of the collection. Every number below is included in the same dated profile snapshot.</p>
                    </div>
                </header>

                <div class="psn-cabinet">
                    <article class="psn-trophy psn-trophy--platinum">
                        <div class="psn-trophy-top">
                            <span class="psn-trophy-medal" aria-hidden="true">PL</span>
                            <span class="psn-trophy-type">Platinum</span>
                        </div>
                        <strong class="psn-trophy-value" data-stat="platinum">10</strong>
                        <span class="psn-trophy-label">Platinum trophies</span>
                    </article>

                    <article class="psn-trophy psn-trophy--gold">
                        <div class="psn-trophy-top">
                            <span class="psn-trophy-medal" aria-hidden="true">AU</span>
                            <span class="psn-trophy-type">Gold</span>
                        </div>
                        <strong class="psn-trophy-value" data-stat="gold">75</strong>
                        <span class="psn-trophy-label">Gold trophies</span>
                    </article>

                    <article class="psn-trophy psn-trophy--silver">
                        <div class="psn-trophy-top">
                            <span class="psn-trophy-medal" aria-hidden="true">AG</span>
                            <span class="psn-trophy-type">Silver</span>
                        </div>
                        <strong class="psn-trophy-value" data-stat="silver">307</strong>
                        <span class="psn-trophy-label">Silver trophies</span>
                    </article>

                    <article class="psn-trophy psn-trophy--bronze">
                        <div class="psn-trophy-top">
                            <span class="psn-trophy-medal" aria-hidden="true">BR</span>
                            <span class="psn-trophy-type">Bronze</span>
                        </div>
                        <strong class="psn-trophy-value" data-stat="bronze">1,583</strong>
                        <span class="psn-trophy-label">Bronze trophies</span>
                    </article>
                </div>
            </section>

            <section class="psn-section" aria-labelledby="source-title">
                <div class="psn-source">
                    <div class="psn-source-copy">
                        <h2 class="psn-source-title" id="source-title" data-i18n="k19">Continue to the source profile</h2>
                        <p class="psn-source-text" data-i18n="k20">PSNProfiles remains the destination for the complete game list, rankings and future trophy updates. This page is a curated snapshot inside kohandezh.com.</p>
                    </div>
                    <a class="psn-button psn-button--primary" href="https://psnprofiles.com/Kohandezh/" target="_blank" rel="noopener noreferrer">
                        Open PSNProfiles
                        <svg viewBox="0 0 20 20" fill="none" aria-hidden="true">
                            <path d="M7 13 13 7M8.25 7H13v4.75" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </a>
                </div>
            </section>
        </main>

        <footer class="psn-footer">
      <div class="kdcv-foot">
        <a class="kdcv-foot-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="Mohammad Ali Kohandezh">
          <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="36" height="36" alt="">
          <span>Mohammad Ali Kohandezh</span>
        </a>
        <nav class="kdcv-foot-nav" aria-label="Site">
          <a href="blog/index.html">Blog</a>
          <a href="<?php echo esc_url( home_url('/portfolio/') ); ?>">Portfolio</a>
          <a href="<?php echo esc_url( home_url('/certificates/') ); ?>">Certificates</a>
          <a href="<?php echo esc_url( home_url('/psn/') ); ?>">PSN Trophy Room</a>
          <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">Privacy Policy</a>
          <a href="<?php echo esc_url( home_url('/terms/') ); ?>">Terms of Use</a>
        </nav>
        <p class="kdcv-foot-legal">All rights reserved<br>© 2026 Mohammad Ali Kohandezh</p>
      </div>
        </footer>
    </div>

    <script>
        (() => {
            const formatNumber = new Intl.NumberFormat("en-US");
            const statNodes = (key) => document.querySelectorAll(`[data-stat="${key}"]`);
            const setStat = (key, value) => statNodes(key).forEach((node) => { node.textContent = value; });

            document.querySelectorAll("[data-current-year]").forEach((node) => {
                node.textContent = new Date().getFullYear();
            });

            try {
                const referrer = new URL(document.referrer);
                const localPages = /\/(?:index|fa|ar|de|fr|es|tr|zh)\.html$/i;
                if (referrer.origin === window.location.origin && localPages.test(referrer.pathname)) {
                    document.querySelectorAll("[data-back-link]").forEach((link) => {
                        link.href = `${referrer.pathname}${referrer.search}${referrer.hash}`;
                    });
                }
            } catch (_) {
                // The static index.html fallback remains valid when there is no referrer.
            }

            if (window.location.protocol === "file:") return;

            fetch("<?php echo KDCV; ?>/assets/data/psn-kohandezh.json", { cache: "no-store" })
                .then((response) => {
                    if (!response.ok) throw new Error("PSN snapshot unavailable");
                    return response.json();
                })
                .then((data) => {
                    setStat("level", formatNumber.format(data.level));
                    setStat("games", formatNumber.format(data.games));
                    setStat("completion", data.completion);
                    setStat("total", formatNumber.format(data.trophies.total));
                    setStat("points", formatNumber.format(data.points));
                    setStat("platinum", formatNumber.format(data.trophies.platinum));
                    setStat("gold", formatNumber.format(data.trophies.gold));
                    setStat("silver", formatNumber.format(data.trophies.silver));
                    setStat("bronze", formatNumber.format(data.trophies.bronze));

                    const snapshotDate = new Date(`${data.fetchedAt}T00:00:00Z`);
                    document.querySelectorAll("[data-snapshot-date]").forEach((node) => {
                        node.dateTime = data.fetchedAt;
                        node.textContent = snapshotDate.toLocaleDateString("en-US", {
                            year: "numeric",
                            month: "long",
                            day: "numeric",
                            timeZone: "UTC"
                        });
                    });
                })
                .catch(() => {
                    // The verified values embedded in the HTML remain as a resilient fallback.
                });
        })();
    </script>
<script>
(function(){
  function msg(lang){
    var m = {
      en: "Right-click is disabled",
      fa: "راست‌کلیک نداریم",
      ar: "لا يوجد زر يمين",
      de: "Rechtsklick deaktiviert",
      es: "Clic derecho desactivado",
      fr: "Clic droit désactivé",
      tr: "Sağ tık devre dışı",
      zh: "右键已禁用",
      ja: "右クリックは無効です"
    };
    return m[lang] || m.en;
  }
  function toast(text){
    var old = document.getElementById('kdcv-nocontext-toast');
    if (old) old.remove();
    var el = document.createElement('div');
    el.id = 'kdcv-nocontext-toast';
    el.textContent = text;
    el.style.cssText = 'position:fixed;left:50%;bottom:32px;transform:translateX(-50%) translateY(20px);background:rgba(11,18,18,.92);color:#6cf3a4;padding:12px 22px;border-radius:12px;font:600 13px/1.4 -apple-system,system-ui,sans-serif;letter-spacing:.02em;z-index:2147483647;box-shadow:0 8px 24px rgba(0,0,0,.4);opacity:0;transition:opacity 180ms ease,transform 220ms cubic-bezier(.2,.8,.2,1);pointer-events:none;-webkit-backdrop-filter:blur(8px);backdrop-filter:blur(8px);border:1px solid rgba(108,243,164,.25)';
    document.body.appendChild(el);
    requestAnimationFrame(function(){
      el.style.opacity = '1';
      el.style.transform = 'translateX(-50%) translateY(0)';
    });
    setTimeout(function(){
      el.style.opacity = '0';
      el.style.transform = 'translateX(-50%) translateY(20px)';
      setTimeout(function(){ el.remove(); }, 220);
    }, 2200);
  }
  function speak(text, lang){
    if (!('speechSynthesis' in window) || typeof window.SpeechSynthesisUtterance !== 'function') return;
    try {
      window.speechSynthesis.cancel();
      var u = new window.SpeechSynthesisUtterance(text);
      var langMap = {en:'en-US',fa:'fa-IR',ar:'ar-SA',de:'de-DE',es:'es-ES',fr:'fr-FR',tr:'tr-TR',zh:'zh-CN',ja:'ja-JP'};
      u.lang = langMap[lang] || 'en-US';
      u.rate = 0.95;
      u.pitch = 0.85;
      var voices = window.speechSynthesis.getVoices() || [];
      var v = voices.find(function(vx){ return String(vx.lang||'').toLowerCase().split('-')[0] === lang; });
      if (v) u.voice = v;
      window.speechSynthesis.speak(u);
    } catch(e){}
  }
  function triggerWeapon(){
    if (!window.KohanAvatar || !window.KohanAvatar.play) return;
    try {
      // Temporarily enable weapon moods so the avatar draws steel
      if (window.KohanAvatar.setOptions) {
        window.KohanAvatar.setOptions({ enableWeaponMoods: true });
      }
      // 65% chance russian-roulette (the dramatic camera-facing draw),
      // 35% chance guarded (low-ready hold). Both are fictional/non-graphic.
      var mood = Math.random() < 0.65 ? 'russian-roulette' : 'guarded';
      window.KohanAvatar.play(mood, { duration: 3200, returnTo: 'idle' });
      // Disable weapon moods again for normal operation
      setTimeout(function(){
        if (window.KohanAvatar && window.KohanAvatar.setOptions) {
          window.KohanAvatar.setOptions({ enableWeaponMoods: false });
        }
      }, 3500);
    } catch(e){}
  }
  document.addEventListener('contextmenu', function(e){
    e.preventDefault();
    var lang = (document.documentElement.lang || 'en').slice(0,2).toLowerCase();
    var text = msg(lang);
    toast(text);
    speak(text, lang);
    triggerWeapon();
    return false;
  }, true);
})();
</script>
  <script src="<?php echo KDCV; ?>/assets/js/pwa-register.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=107" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/lazy-bundle.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar.min.js?v=126" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar-enhance.min.js?v=113" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-drive.min.js?v=3" defer></script>
<script src="<?php echo KDCV; ?>/assets/js/wisdom-quotes.min.js?v=112" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=15" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=96" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/chat-ui.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/flow-field-background.min.js?v=95" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/hud-button.min.js?v=102" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
