<?php /* KohandezhCV — terms page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!DOCTYPE html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="terms" data-kdcv-i18n-source="fa" lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="شرایط استفاده از kohandezh.com — مالکیت محتوا، محدودیت مسئولیت، استفادهٔ مجاز و تماس.">
  <meta name="theme-color" content="#080b0d">
  <meta name="author" content="Mohammad Ali Kohandezh">
  <meta name="robots" content="index, follow">
  <title>شرایط استفاده | Terms of Use — Kohandezh.com</title>
  <link rel="preload" href="<?php echo KDCV; ?>/assets/fonts/estedad/Estedad-VF.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/icomoon/style.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/blog.min.css?v=105">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/flow-field-background.min.css?v=95">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="<?php echo KDCV; ?>/assets/images/logo/apple-touch-icon.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="canonical" href="https://kohandezh.com/terms/">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@kohandezh">
  <meta name="twitter:title" content="شرایط استفاده | Terms of Use — Kohandezh.com">
  <meta name="twitter:description" content="شرایط استفاده از kohandezh.com — مالکیت محتوا، محدودیت مسئولیت، استفادهٔ مجاز و تماس.">
  <meta name="twitter:image" content="<?php echo KDCV; ?>/assets/images/avatar/avatar-professional.webp">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=99">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/hud-button.min.css?v=103">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=124" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-avatar.min.css?v=124"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=3" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/kohan-drive.min.css?v=3"></noscript>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=108" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/chat-ui.min.css?v=108"></noscript>
  <!-- Breadcrumb trail: lets Google render the path instead of a bare
       URL in results, and gives answer engines the page's place in the
       site rather than treating it as an orphan. -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "خانه",
      "item": "https://kohandezh.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Terms of Use",
      "item": "https://kohandezh.com/terms/"
    }
  ]
}
  </script>
    <?php wp_head(); ?>
</head>
<body class="blog-page">
<?php wp_body_open(); ?>
<script>/* Theme boot — runs before paint so a page never flashes the wrong theme on navigation. Mirrors main.js: stored choice wins, then data-default-mode, then light. `light` is the class portfolio.js uses. */(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <div class="blog-shell">
    <header class="blog-header">
      <a class="blog-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="بازگشت به صفحه اصلی محمدعلی کهن‌دژ">
        <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="MK">
        <span>MOHAMMAD ALI KOHANDEZH</span>
      </a>
      <nav class="blog-nav" aria-label="ناوبری">
        <a href="<?php echo esc_url( home_url('/') ); ?>">صفحه اصلی</a>
        <a href="blog/index.html">وبلاگ</a>
        <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">حریم خصوصی</a>
      </nav>
      <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
        <div class="blog-header-actions">
      </div>
    </header>

    <main>
      <article class="blog-article">
        <header class="blog-article-header">
          <span class="blog-eyebrow" data-i18n="e01">شرایط استفاده</span>
          <h1 data-i18n="k01">شرایط استفاده از وب‌سایت</h1>
          <div class="blog-meta"><span data-i18n="m01">آخرین به‌روزرسانی: مرداد ۱۴۰۵</span><span data-i18n="m02">Terms of Use</span></div>
        </header>

        <div class="blog-article-body">
          <p data-i18n="k02">با استفاده از <strong>kohandezh.com</strong> شرایط زیر را می‌پذیرید. این سایت یک وب‌سایت شخصی و حرفه‌ای است که برای معرفی سوابق، نوشته‌ها و خدمات محمدعلی کهن‌دژ منتشر می‌شود.</p>

          <h2 id="content" data-i18n="k03">مالکیت محتوا</h2>
          <p data-i18n="k04">متن‌ها، تصاویر، نشان‌ها و طراحی این سایت متعلق به محمدعلی کهن‌دژ است، مگر آنکه خلاف آن ذکر شده باشد. نقل‌قول کوتاه همراه با ذکر منبع و پیوند به صفحهٔ اصلی آزاد است. بازنشر کامل یک نوشته، استفادهٔ تجاری یا انتشار مجدد بدون اجازهٔ کتبی مجاز نیست.</p>
          <p data-i18n="k05">نام‌ها و نشان‌های تجاری اشخاص ثالث (مانند VMware، LinkedIn، آپارات و مانند آن) متعلق به مالکان خودشان است و صرفاً برای اشاره به کار می‌روند.</p>

          <h2 id="videos" data-i18n="k06">ویدئوها و محتوای رسانه‌ای</h2>
          <p data-i18n="k07">ویدئوهای مصاحبه از طریق آپارات نمایش داده می‌شوند و حقوق آن‌ها نزد تولیدکنندهٔ اصلی برنامه باقی می‌ماند. پیوند به منبع اصلی در هر نوشته آمده است.</p>

          <h2 id="accuracy" data-i18n="k08">دقت محتوا و ماهیت مطالب</h2>
          <p data-i18n="k09">نوشته‌های این سایت دیدگاه شخصی نویسنده در زمان انتشار است. تلاش می‌شود مطالب دقیق باشند، اما هیچ تضمینی دربارهٔ کامل‌بودن یا به‌روزبودن آن‌ها داده نمی‌شود.</p>
          <p data-i18n="k10"><strong>این مطالب مشاورهٔ حقوقی، مالی، سرمایه‌گذاری یا پزشکی نیستند</strong> و نباید مبنای تصمیم‌های حرفه‌ای قرار گیرند. برای تصمیم‌های سازمانی، مشاورهٔ تخصصی متناسب با شرایط خودتان بگیرید.</p>

          <h2 id="ai" data-i18n="k11">دستیار گفت‌وگوی هوش مصنوعی</h2>
          <p data-i18n="k12">در صورت فعال‌بودن، ویجت گفت‌وگو پاسخ‌ها را به‌صورت خودکار تولید می‌کند. خروجی مدل‌های زبانی ممکن است نادرست یا ناقص باشد و پاسخ‌ها جایگزین گفت‌وگوی مستقیم نیستند. اطلاعات محرمانه یا حساس را در این ویجت وارد نکنید.</p>

          <h2 id="use" data-i18n="k13">استفادهٔ مجاز</h2>
          <p data-i18n="k14">هنگام استفاده از سایت، از موارد زیر خودداری کنید:</p>
          <ul>
            <li data-i18n="k15">تلاش برای نفوذ، اسکن یا اختلال در عملکرد سایت و زیرساخت آن.</li>
            <li data-i18n="k16">استخراج خودکار انبوه محتوا (scraping) بدون اجازه.</li>
            <li data-i18n="k17">ارسال محتوای غیرقانونی، توهین‌آمیز یا هرزنامه از طریق فرم تماس.</li>
            <li data-i18n="k18">جعل هویت یا ارائهٔ اطلاعات تماس نادرست.</li>
          </ul>

          <h2 id="links" data-i18n="k19">پیوندهای بیرونی</h2>
          <p data-i18n="k20">این سایت به منابع بیرونی پیوند می‌دهد. مسئولیت محتوا، سیاست‌ها و امنیت آن سایت‌ها بر عهدهٔ خودشان است.</p>

          <h2 id="liability" data-i18n="k21">محدودیت مسئولیت</h2>
          <p data-i18n="k22">استفاده از این سایت بر عهدهٔ خود شماست. تا حدی که قانون اجازه می‌دهد، هیچ مسئولیتی بابت خسارت‌های مستقیم یا غیرمستقیم ناشی از استفاده یا عدم دسترسی به سایت پذیرفته نمی‌شود. سایت «همان‌گونه که هست» ارائه می‌شود و در دسترس‌بودن دائمی آن تضمین نمی‌شود.</p>

          <h2 id="privacy" data-i18n="k23">حریم خصوصی</h2>
          <p data-i18n="k24">نحوهٔ برخورد با داده‌های شما در <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">سیاست حریم خصوصی</a> توضیح داده شده است؛ آن صفحه بخشی از همین شرایط محسوب می‌شود.</p>

          <h2 id="changes" data-i18n="k25">تغییرات</h2>
          <p data-i18n="k26">این شرایط ممکن است به‌روزرسانی شود. تاریخ آخرین تغییر در بالای صفحه درج می‌شود و ادامهٔ استفاده از سایت به معنای پذیرش نسخهٔ جدید است.</p>

          <h2 id="contact" data-i18n="k27">تماس</h2>
          <p data-i18n="k28">برای هر پرسشی دربارهٔ این شرایط، از <a href="index.html#contact">فرم تماس</a> استفاده کنید.</p>

          <hr data-kdcv-i18n-drop>

          <h2 id="en" lang="en" dir="ltr" data-kdcv-i18n-drop data-i18n="k29">Terms of Use (English summary)</h2>
          <div lang="en" dir="ltr" data-kdcv-i18n-drop>
            <p data-i18n="k30">By using <strong>kohandezh.com</strong> you accept these terms. This is a personal and professional site presenting the work, writing and services of Mohammad Ali Kohandezh.</p>
            <p data-i18n="k31"><strong>Content ownership:</strong> text, images, marks and design belong to Mohammad Ali Kohandezh unless stated otherwise. Short quotations with attribution and a link are welcome; full republication or commercial use requires written permission. Third-party trademarks belong to their respective owners.</p>
            <p data-i18n="k32"><strong>Interview videos</strong> are embedded from Aparat and remain the property of the original producers.</p>
            <p data-i18n="k33"><strong>No professional advice:</strong> posts reflect personal opinion at the time of writing and are not legal, financial, investment or medical advice.</p>
            <p data-i18n="k34"><strong>AI assistant:</strong> where enabled, responses are generated automatically and may be inaccurate or incomplete. Do not enter confidential information.</p>
            <p data-i18n="k35"><strong>Acceptable use:</strong> no intrusion attempts, bulk scraping, spam, or impersonation.</p>
            <p data-i18n="k36"><strong>Liability:</strong> the site is provided "as is", without warranty of continuous availability. To the extent permitted by law, no liability is accepted for damages arising from its use or unavailability.</p>
            <p data-i18n="k37">Questions? Use the <a href="index.html#contact">contact form</a>.</p>
          </div>
        </div>

        <footer class="blog-article-footer">

          <a class="blog-read" href="<?php echo esc_url( home_url('/privacy/') ); ?>">سیاست حریم خصوصی <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
          <a class="blog-read" href="<?php echo esc_url( home_url('/') ); ?>">بازگشت به صفحه اصلی <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
        </footer>
      </article>
    </main>

    <footer class="blog-footer">
      <div class="kdcv-foot">
        <a class="kdcv-foot-brand" href="<?php echo esc_url( home_url('/') ); ?>" aria-label="Mohammad Ali Kohandezh">
          <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="36" height="36" alt="">
          <span>Mohammad Ali Kohandezh</span>
        </a>
        <nav class="kdcv-foot-nav" aria-label="Site">
          <a href="blog/index.html">Blog</a>
          <a href="<?php echo esc_url( home_url('/portfolio/') ); ?>">Portfolio</a>
          <a href="<?php echo esc_url( home_url('/certificates/') ); ?>">Certificates</a>
          <a href="<?php echo esc_url( home_url('/psn/') ); ?>">PSN Trophy Room</a>
          <a href="<?php echo esc_url( home_url('/privacy/') ); ?>">Privacy Policy</a>
          <a href="<?php echo esc_url( home_url('/terms/') ); ?>">Terms of Use</a>
        </nav>
        <p class="kdcv-foot-legal">All rights reserved<br>© 2026 Mohammad Ali Kohandezh</p>
      </div>
    </footer>
  </div>
  <script src="<?php echo KDCV; ?>/assets/js/pwa-register.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/flow-field-background.min.js?v=95" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=107" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/lazy-bundle.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar.min.js?v=126" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-avatar-enhance.min.js?v=112" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/kohan-drive.min.js?v=2" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=15" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=96" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/chat-ui.min.js?v=111" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/hud-button.min.js?v=102" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
