<?php /* KohandezhCV — knowledge page (generated by sync-from-static.py, do not hand-edit) */ ?>
<!doctype html>
<html data-kdcv-i18n="in-place" data-kdcv-i18n-page="knowledge" data-kdcv-i18n-source="en" lang="en" dir="ltr" data-kdcv-router-mode="wordpress" data-kdcv-site-base="<?php echo esc_url(home_url('/')); ?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="The advisory map Mohammad Ali Kohandezh works from: a knowledge tree of applied AI and quantum readiness, and where an outside specialist adds value.">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <meta name="theme-color" content="#080b0d">
  <title>Knowledge Tree — AI &amp; Quantum Advisory | Mohammad Ali Kohandezh</title>
  <link rel="preload" href="<?php echo KDCV; ?>/assets/fonts/estedad/Estedad-VF.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/estedad/estedad.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/fonts/inter/inter.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/icomoon/style.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/icon/simple-line/simple-line.css">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/blog.min.css?v=105">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/knowledge.min.css?v=1">
  <link rel="stylesheet" href="<?php echo KDCV; ?>/assets/css/page-chrome.min.css?v=99">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo KDCV; ?>/assets/images/logo/favicon-32.png?v=2">
  <link rel="canonical" href="https://kohandezh.com/knowledge/">
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "name": "Knowledge Tree — AI & Quantum Advisory",
    "url": "https://kohandezh.com/knowledge/",
    "author": { "@type": "Person", "@id": "https://kohandezh.com/#person", "name": "Mohammad Ali Kohandezh" },
    "about": [
      { "@type": "Thing", "name": "Applied artificial intelligence" },
      { "@type": "Thing", "name": "Post-quantum cryptography readiness" }
    ],
    "hasPart": [
      { "@type": "DefinedTermSet", "name": "Applied AI knowledge tree", "description": "Foundations, retrieval and grounding, agentic systems, and enterprise adoption." },
      { "@type": "DefinedTermSet", "name": "Quantum readiness knowledge tree", "description": "Fundamentals, the harvest-now-decrypt-later threat model, post-quantum standards, and migration programme." }
    ]
  }
  </script>
    <?php wp_head(); ?>
</head>
<body class="blog-page">
<?php wp_body_open(); ?>
<script>(function(){try{var s=localStorage.getItem("darkMode"),d;if(s!==null){d=s==="enabled";}else{d=document.body.getAttribute("data-default-mode")==="dark";}document.body.classList.toggle("dark-mode",d);document.body.classList.toggle("light",!d);document.documentElement.setAttribute("data-kdcv-theme",d?"dark":"light");}catch(e){}})();</script>
  <div class="blog-shell">
    <header class="blog-header">
      <a class="blog-brand" href="<?php echo esc_url( home_url('/') ); ?>" data-i18n-aria="a_home" aria-label="Back to Mohammad Ali Kohandezh's home page">
        <img src="<?php echo KDCV; ?>/assets/images/logo/logo.webp" width="40" height="40" alt="MK">
        <span>MOHAMMAD ALI KOHANDEZH</span>
      </a>
      <nav class="blog-nav" data-i18n-aria="a_nav" aria-label="Knowledge hub navigation">
        <a href="blog/index.html" data-i18n="k01">All posts</a>
      </nav>
      <div class="time-local text-body-3"><p class="date"></p><p class="clock"></p></div>
      <div class="blog-header-actions">
        <a href="index.html#contact" data-i18n-aria="a_chat" aria-label="Start a conversation" data-i18n="k02"><i class="icon icon-send"></i><span>Start a conversation</span></a>
      </div>
    </header>

    <main>
      <article class="blog-article kh-page">

        <header class="blog-article-header kh-hero">
          <span class="blog-eyebrow" data-i18n="h_eyebrow">AI &amp; quantum advisory</span>
          <h1 data-i18n="h_title">The map I work from</h1>
          <p class="kh-lead" data-i18n="h_lead">Two technologies are arriving on very different timelines, and both land in the same place: the infrastructure an organization already depends on. This is the territory as I actually work it — what each field is made of, and the point at which an outside specialist earns their fee.</p>
          <div class="kh-hero-actions">
            <a class="kh-cta" href="index.html#contact" data-i18n="h_cta">Discuss an engagement <i class="icon icon-arrow-right-top" aria-hidden="true"></i></a>
            <a class="kh-cta kh-cta--ghost" href="<?php echo esc_url( home_url('/certificates/') ); ?>" data-i18n="h_cta2">See the credentials behind it</a>
          </div>
        </header>

        <div class="kh-tabs" role="tablist" data-i18n-aria="a_tabs" aria-label="Knowledge domains">
          <button type="button" role="tab" id="kh-tab-ai" aria-controls="kh-panel-ai" aria-selected="true" tabindex="0" class="kh-tab">
            <span class="kh-tab-label" data-i18n="tab_ai">Artificial intelligence</span>
            <span class="kh-tab-sub" data-i18n="tab_ai_sub">Here now</span>
          </button>
          <button type="button" role="tab" id="kh-tab-q" aria-controls="kh-panel-q" aria-selected="false" tabindex="-1" class="kh-tab">
            <span class="kh-tab-label" data-i18n="tab_q">Quantum readiness</span>
            <span class="kh-tab-sub" data-i18n="tab_q_sub">Arriving</span>
          </button>
        </div>

        <!-- ── AI panel ──────────────────────────────────────────────────── -->
        <section class="kh-panel" role="tabpanel" id="kh-panel-ai" aria-labelledby="kh-tab-ai">
          <div class="kh-root">
            <span class="kh-root-kicker" data-i18n="ai_kicker">Domain</span>
            <h2 class="kh-root-name" data-i18n="ai_name">Applied artificial intelligence</h2>
            <p class="kh-root-desc" data-i18n="ai_intro">Almost every organization can now buy a model. Very few can say what it is allowed to touch, where its answers come from, or what happens when it is wrong. Those three questions are the whole job, and they are infrastructure questions before they are AI questions.</p>
          </div>

          <ol class="kh-tree" role="list">
            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">01</span>
                <h3 class="kh-branch-title" data-i18n="a1t">Foundations</h3>
                <span class="kh-eng" data-i18n="eng_advisory">Advisory</span>
              </div>
              <p class="kh-branch-desc" data-i18n="a1d">What the machine is actually doing, stated plainly enough to make decisions on. Without this, every later choice is guesswork dressed as strategy.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="a1l1">Tokens &amp; context windows</li>
                <li data-i18n="a1l2">Training vs inference</li>
                <li data-i18n="a1l3">Why models hallucinate</li>
                <li data-i18n="a1l4">Prompting as specification</li>
                <li data-i18n="a1l5">Evaluating an answer</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">02</span>
                <h3 class="kh-branch-title" data-i18n="a2t">Knowledge &amp; retrieval</h3>
                <span class="kh-eng" data-i18n="eng_design">Design</span>
              </div>
              <p class="kh-branch-desc" data-i18n="a2d">Making a model answer from your facts rather than its memory. This is the pattern behind almost every serious enterprise assistant — including the one on this site.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="a2l1">Retrieval-augmented generation</li>
                <li data-i18n="a2l2">Chunking &amp; embeddings</li>
                <li data-i18n="a2l3">Vector stores</li>
                <li data-i18n="a2l4">Source attribution</li>
                <li data-i18n="a2l5">Data governance &amp; residency</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">03</span>
                <h3 class="kh-branch-title" data-i18n="a3t">Agentic systems</h3>
                <span class="kh-eng" data-i18n="eng_delivery">Delivery</span>
              </div>
              <p class="kh-branch-desc" data-i18n="a3d">Software that plans, calls tools and completes work. The frontier, and the point where AI stops being a text problem and becomes a security-engineering problem.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="a3l1">Tool calling &amp; function schemas</li>
                <li data-i18n="a3l2">Orchestration &amp; task decomposition</li>
                <li data-i18n="a3l3">Guardrails &amp; sandboxing</li>
                <li data-i18n="a3l4">Human-in-the-loop checkpoints</li>
                <li data-i18n="a3l5">Failure containment &amp; rollback</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">04</span>
                <h3 class="kh-branch-title" data-i18n="a4t">Enterprise adoption</h3>
                <span class="kh-eng" data-i18n="eng_enable">Enablement</span>
              </div>
              <p class="kh-branch-desc" data-i18n="a4d">Everything that decides whether a working pilot survives contact with a real organization: who it authenticates as, what it costs, and who is accountable when it errs.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="a4l1">Identity &amp; least privilege</li>
                <li data-i18n="a4l2">Observability &amp; audit trails</li>
                <li data-i18n="a4l3">Cost &amp; capacity control</li>
                <li data-i18n="a4l4">Vendor &amp; model selection</li>
                <li data-i18n="a4l5">Change management &amp; training</li>
              </ul>
            </li>
          </ol>

          <p class="kh-note" data-i18n="ai_note"><strong>Field note:</strong> in the programmes we run at Kohan System Farda, the people who advance fastest are rarely the most technical. They are the ones who kept a daily log of what worked and what failed — and an agent is only ever as trustworthy as the infrastructure underneath it.</p>
        </section>

        <!-- ── Quantum panel ─────────────────────────────────────────────── -->
        <section class="kh-panel" role="tabpanel" id="kh-panel-q" aria-labelledby="kh-tab-q" hidden>
          <div class="kh-root">
            <span class="kh-root-kicker" data-i18n="q_kicker">Domain</span>
            <h2 class="kh-root-name" data-i18n="q_name">Quantum readiness</h2>
            <p class="kh-root-desc" data-i18n="q_intro">Nothing here depends on owning a quantum computer. It depends on one question a board can answer today: how long must this data stay secret? Anything sensitive beyond 2030 already needs a plan, because the data being stolen now can be decrypted later.</p>
          </div>

          <ol class="kh-tree" role="list">
            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">01</span>
                <h3 class="kh-branch-title" data-i18n="q1t">Fundamentals</h3>
                <span class="kh-eng" data-i18n="eng_advisory">Advisory</span>
              </div>
              <p class="kh-branch-desc" data-i18n="q1d">The honest state of the hardware, without the popular-science mystique. A quantum computer is fast at a narrow class of problems, and slow to arrive — both halves matter.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="q1l1">Qubits &amp; superposition</li>
                <li data-i18n="q1l2">Entanglement</li>
                <li data-i18n="q1l3">Error correction as the bottleneck</li>
                <li data-i18n="q1l4">Reading qubit-count claims</li>
                <li data-i18n="q1l5">Where advantage is real</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">02</span>
                <h3 class="kh-branch-title" data-i18n="q2t">The threat model</h3>
                <span class="kh-eng" data-i18n="eng_assess">Assessment</span>
              </div>
              <p class="kh-branch-desc" data-i18n="q2d">Why a security professional cannot postpone this. Encrypted traffic captured today can be stored and opened once the hardware matures — the risk is set by your data's lifetime, not by the vendor's roadmap.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="q2l1">Harvest now, decrypt later</li>
                <li data-i18n="q2l2">RSA &amp; Diffie-Hellman</li>
                <li data-i18n="q2l3">Elliptic-curve exposure</li>
                <li data-i18n="q2l4">What survives: AES-256, SHA-2</li>
                <li data-i18n="q2l5">Data-lifetime analysis</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">03</span>
                <h3 class="kh-branch-title" data-i18n="q3t">Post-quantum cryptography</h3>
                <span class="kh-eng" data-i18n="eng_design">Design</span>
              </div>
              <p class="kh-branch-desc" data-i18n="q3d">The replacements are standardized, not theoretical. NIST has published them; the work now is choosing correctly and deploying without breaking what already runs.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="q3l1">ML-KEM for key exchange</li>
                <li data-i18n="q3l2">ML-DSA for signatures</li>
                <li data-i18n="q3l3">SLH-DSA as a conservative fallback</li>
                <li data-i18n="q3l4">Hybrid classical + PQC modes</li>
                <li data-i18n="q3l5">Certificate &amp; TLS impact</li>
              </ul>
            </li>

            <li class="kh-branch">
              <div class="kh-branch-head">
                <span class="kh-no" aria-hidden="true">04</span>
                <h3 class="kh-branch-title" data-i18n="q4t">Migration programme</h3>
                <span class="kh-eng" data-i18n="eng_delivery">Delivery</span>
              </div>
              <p class="kh-branch-desc" data-i18n="q4d">Turning a standard into a plan with dates. Most organizations cannot answer where their cryptography lives, and that inventory is the first deliverable, not the last.</p>
              <ul class="kh-leaves" role="list">
                <li data-i18n="q4l1">Cryptographic inventory</li>
                <li data-i18n="q4l2">Crypto-agility by design</li>
                <li data-i18n="q4l3">Vendor migration roadmaps</li>
                <li data-i18n="q4l4">Prioritizing by data lifetime</li>
                <li data-i18n="q4l5">Pilot, rollout &amp; verification</li>
              </ul>
            </li>
          </ol>

          <p class="kh-note" data-i18n="q_note"><strong>Field note:</strong> when I audit infrastructure I now ask one added question — how long must this data stay secret? It reframes the conversation from a physics debate the board cannot settle into a records-retention decision it already knows how to make.</p>
        </section>

        <!-- ── engagement ────────────────────────────────────────────────── -->
        <section class="kh-work">
          <h2 class="kh-work-h" data-i18n="w_h">How I work with organizations</h2>
          <div class="kh-work-grid">
            <div class="kh-work-item">
              <h3 data-i18n="w1t">Assess</h3>
              <p data-i18n="w1d">A short, evidence-based read of where you stand: what AI is already in use unofficially, where cryptography lives, and which data has a lifetime long enough to matter.</p>
            </div>
            <div class="kh-work-item">
              <h3 data-i18n="w2t">Design</h3>
              <p data-i18n="w2d">An architecture your team can build and defend — retrieval and permissions for AI, crypto-agility for the quantum side — sized to the organization you actually have.</p>
            </div>
            <div class="kh-work-item">
              <h3 data-i18n="w3t">Enable</h3>
              <p data-i18n="w3d">Handover that outlasts the engagement: your people trained, the decisions written down, and a roadmap with dates rather than intentions.</p>
            </div>
          </div>
          <p class="kh-work-foot" data-i18n="w_foot">If one branch of either tree is a live question for your organization, that is a good place to start the conversation.</p>
        </section>

        <footer class="blog-article-footer">
          <a class="blog-read" href="index.html#contact" data-i18n="k29">Start a conversation <i class="icon icon-arrow-right-top"></i></a>
          <a class="blog-read" href="blog/index.html" data-i18n="k28">All posts <i class="icon icon-arrow-right-top"></i></a>
        </footer>
      </article>
    </main>

    <footer class="blog-footer"></footer>
  </div>
  <script src="<?php echo KDCV; ?>/assets/js/clock.min.js?v=106" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-i18n.min.js?v=15" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/knowledge-tabs.min.js?v=1" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-chrome.min.js?v=96" defer></script>
  <script src="<?php echo KDCV; ?>/assets/js/page-context.min.js?v=107" defer></script>
    <?php wp_footer(); ?>
</body>
</html>
