#!/usr/bin/env python3
"""
Stamp the "Waiting" page loader (the MK-logo loading motion) into every page.

WHAT IT IS
----------
One self-contained block -- inline <style>, markup, inline <script> -- placed
IMMEDIATELY after the opening <body ...> tag. The single source of truth is
_tooling/waiting/waiting.partial.html. Never edit the block inside a page: the
next run of this script replaces it.

WHY INLINE
----------
* It has to paint with the very first frame, before any external stylesheet or
  script has arrived. An external file would be the thing it is waiting for.
* The static site and WordPress resolve asset URLs differently
  (assets/... vs wp-content/themes/kohandezhcv/assets/...). The block carries no
  URL at all -- the logo is the vector from assets/images/logo/logo.svg inlined --
  so that split cannot break it. validate_partial() enforces this.

DISMISSAL CONTRACT (implemented by the script inside the partial)
-----------------------------------------------------------------
* Leaves at window "load", or when the parser finishes (readyState
  "interactive", i.e. BEFORE the ~37 deferred scripts) plus a cap of 1200 ms on
  the first view of the session and 0 ms on every later view -- whichever is
  first.
* Never before the first-view minimum of 940 ms (the end of the entry motion),
  so the motion reads once per session (sessionStorage "kdcvWaitingSeen"). The
  minimum is 0 on repeat views and under prefers-reduced-motion.
* JS hard cap 3 s. Any keydown or pointerdown dismisses at once.
* The caps are re-checked on every capture-phase "load" event of the page's own
  scripts, styles and images, not only by timers: Chrome starves setTimeout
  while the deferred scripts load, and timers alone released the overlay only at
  DOMContentLoaded (measured on the dev server).
* Removed immediately when readyState is already "complete", on a bfcache
  restore (pageshow.persisted) and for crawler user agents.
* Cannot trap the visitor: a CSS-only failsafe hides it at 6 s even if the script
  never runs or throws, and <noscript> hides it outright. The failsafe animation
  and the JS fade are independent properties, so neither can undo the other.

TARGETS
-------
Static pages listed in STATIC plus every blog/*.html post; the hand-maintained
WordPress templates home.php and single.php (after their wp_body_open() call);
and the local preview page. The generated WP templates (front-page.php,
page-*.php, 404.php) inherit the block through sync-from-static.py. The
404-*.html redirect stubs and offline.html (service-worker fallback) are
deliberately excluded: a stub navigates away at once and the offline page must
render with nothing else available.

    python3 _tooling/waiting/build.py [--check]

Idempotent. --check exits non-zero listing out-of-date files, without writing.
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PARTIAL = os.path.join(ROOT, '_tooling', 'waiting', 'waiting.partial.html')

BEGIN = ('<!-- WAITING:BEGIN generated from _tooling/waiting/waiting.partial.html '
         'by _tooling/waiting/build.py -- do not edit by hand -->')
END = '<!-- WAITING:END -->'
BEGIN_ANY = '<!-- WAITING:BEGIN'

CV = ['index.html', 'fa.html', 'ar.html', 'de.html', 'es.html',
      'fr.html', 'tr.html', 'zh.html', 'ja.html', 'ru.html']
STATIC = CV + ['Certificates.html', 'PSN.html', 'knowledge.html', 'privacy.html',
               'terms.html', 'videos.html', '404.html', 'portfolio/index.html']
WP_HAND = ['_tooling/wp-theme/kohandezhcv/home.php',
           '_tooling/wp-theme/kohandezhcv/single.php',
           # The book reader is the plugin's own full page, not a theme template.
           '_tooling/wp-theme/kohandezh-knowledge/templates/ai-book.php']
PREVIEW = ['_tooling/waiting/preview.html']
EXCLUDED_FIXED = ['offline.html']

# A PHP template can echo inside the tag (<body class="<?php ... ?>">): its "?>"
# is not the end of the tag, so PHP blocks are consumed whole before the real ">".
BODY_RE = re.compile(r'<body(?=[\s>])(?:<\?php.*?\?>|[^>])*>', re.I | re.S)
WP_BODY_OPEN_RE = re.compile(r'[ \t]*\n?[ \t]*<\?php\s+wp_body_open\(\s*\)\s*;\s*\?>')
COMMENT_RE = re.compile(r'<!--.*?-->', re.S)
BLOCK_RE = re.compile(r'\n?[ \t]*' + re.escape(BEGIN_ANY) + r'\b.*?' + re.escape(END), re.S)


class StampError(Exception):
    pass


def rel(path):
    return os.path.relpath(path, ROOT)


def targets():
    """Every file that must carry the block, in a stable order."""
    names = list(STATIC)
    names += sorted(rel(p) for p in glob.glob(os.path.join(ROOT, 'blog', '*.html')))
    # The static book shell (generated by _tooling/ai-book/build_visual_shell.py,
    # which emits the block itself).
    names += sorted(rel(p) for p in glob.glob(os.path.join(ROOT, 'books', '**', 'index.html'), recursive=True))
    names += WP_HAND + PREVIEW
    missing = [n for n in names if not os.path.isfile(os.path.join(ROOT, n))]
    if missing:
        raise StampError('target(s) missing: ' + ', '.join(missing))
    return names


def excluded():
    """Pages that must NOT carry the block (stripped if one ever appears)."""
    stubs = sorted(rel(p) for p in glob.glob(os.path.join(ROOT, '404-*.html')))
    return [n for n in stubs + EXCLUDED_FIXED if os.path.isfile(os.path.join(ROOT, n))]


def validate_partial(text):
    block = text.rstrip('\n')
    if not block.startswith(BEGIN + '\n') or not block.endswith('\n' + END):
        raise StampError('partial must start with the exact BEGIN marker line and end with the END marker line')
    if block.count(BEGIN_ANY) != 1 or block.count(END) != 1:
        raise StampError('partial must contain exactly one BEGIN and one END marker')
    # Strings that would break sync-from-static.py's one-<body>/<head> assertions,
    # open PHP mode in home.php/single.php, or make the block fetch something.
    for bad in ('<body', '</body', '<head', '</head', '<?', 'src=', 'href=', 'assets/', '@import', 'http:', 'https:'):
        if bad in block.lower():
            raise StampError(f'partial must not contain {bad!r}')
    for url in re.findall(r'url\(([^)]*)\)', block):
        if not url.startswith('#'):
            raise StampError(f'partial may only reference in-document fragments, found url({url})')
    return block


def insertion_point(src, name):
    # Comments are blanked (same length, so offsets hold) before looking for the
    # tag: a comment that merely mentions <body> must not count as one.
    visible = COMMENT_RE.sub(lambda m: ' ' * len(m.group(0)), src)
    bodies = BODY_RE.findall(visible)
    if len(bodies) != 1:
        raise StampError(f'{name}: expected exactly one <body> tag, found {len(bodies)}')
    pos = BODY_RE.search(visible).end()
    # WordPress: the theme/plugins' wp_body_open() output comes first, the loader right after it.
    m = WP_BODY_OPEN_RE.match(src, pos)
    return m.end() if m else pos


def stamp(src, block, name):
    begins, ends = src.count(BEGIN_ANY), src.count(END)
    if begins > 1 or ends > 1:
        raise StampError(f'{name}: more than one WAITING marker pair ({begins} BEGIN, {ends} END)')
    if begins != ends:
        raise StampError(f'{name}: unbalanced WAITING markers ({begins} BEGIN, {ends} END)')
    bare = BLOCK_RE.sub('', src, count=1)
    pos = insertion_point(bare, name)
    return bare[:pos] + '\n' + block + bare[pos:]


def strip(src, name):
    if src.count(BEGIN_ANY) != src.count(END):
        raise StampError(f'{name}: unbalanced WAITING markers')
    return BLOCK_RE.sub('', src)


def main():
    check = '--check' in sys.argv
    # Everything is computed before anything is written: a bad target aborts the
    # whole run instead of leaving the site half-stamped.
    try:
        with open(PARTIAL, encoding='utf-8') as fh:
            block = validate_partial(fh.read())
        jobs = [(n, 'stamp') for n in targets()] + [(n, 'strip') for n in excluded()]
        results = []
        for name, action in jobs:
            path = os.path.join(ROOT, name)
            with open(path, encoding='utf-8', newline='') as fh:
                src = fh.read()
            new = stamp(src, block, name) if action == 'stamp' else strip(src, name)
            results.append((name, action, path, new, new != src))
    except StampError as exc:
        sys.stdout.flush()
        print(f'ERROR: {exc}\nNothing was written.', file=sys.stderr)
        return 2

    stale = []
    for name, action, path, new, changed in results:
        if changed:
            stale.append(name)
            if not check:
                with open(path, 'w', encoding='utf-8', newline='') as fh:
                    fh.write(new)
        state = ('stale' if check else 'wrote') if changed else 'ok   '
        print(f'  {state} {name}' + ('' if action == 'stamp' else ' (excluded: must not carry the loader)'))

    print(f'\nWaiting block: {len(block.encode("utf-8"))} bytes; {len(results)} files checked.')
    if check and stale:
        print(f'\nOut of date: {", ".join(stale)}\nRun: python3 _tooling/waiting/build.py')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
