#!/usr/bin/env python3
"""
Validate a book root against the Kohandezh Book Bundle Format v1
(Books/BOOK-FORMAT.md). Standard library only; read-only.

    python3 _tooling/ai-book/validate_book.py [--root Books/ai-governance]
        [--strict] [--release] [--slug SLUG] [--code CODE] [--json]

--strict   every file must be present: a missing build output (PDF, search
           index) or optional file (overlay, doc titles) is a FAIL.
--release  build outputs must be present (what build_data_zip.py ships);
           optional files stay optional.
--slug     the book's registry slug; default: inferred from canonical_url.
--code     the ID code (KDJ-{CODE}-…); default: inferred from the first ID.
--json     machine-readable report on stdout.

Every check is a named function reporting PASS / WARN / FAIL (or SKIP when
its input is absent) with a count and at most three examples.
Exit: 0 = no FAIL, 1 = at least one FAIL, 2 = usage error.

The hashing rule (kdj-hash-1) is copied from the book pipeline
(Books/ai-governance/tools/master.py content_hash/canonical_text and
tools/verify_release.py); the plugin itself never re-hashes text.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
import unicodedata
from pathlib import Path
from urllib.parse import urlsplit

REPO = Path(__file__).resolve().parents[2]
FORMAT = 'kohandezh-book-bundle/1'

# ---------------------------------------------------------------- the file set
REQUIRED_FILES = [
    'master/book.json', 'master/bibliography.json', 'master/source_map.json',
    'provenance/content_ids.json', 'provenance/citation-registry.json', 'provenance/release-manifest.json',
    'release/09_glossary.json', 'release/14_rag_corpus_fa.jsonl',
    'knowledge/graph.json', 'knowledge/entities.jsonl', 'manifests/sources.json',
]
# Generated by the pipeline and gitignored in the repo (Books/**/*.pdf,
# Books/ai-governance/html/); required in every uploaded bundle.
BUILD_FILES = ['release/06_book_fa.pdf', 'html/search/index.json']
OPTIONAL_FILES = ['master/reader-overlay.json', 'taxonomy/doc_titles_fa.json']
TEMPLATE_GLOB = 'templates/TPL-*.json'
BUNDLE_FILES = REQUIRED_FILES + BUILD_FILES  # + templates + present optional files

# Release-manifest artifact name -> path inside the bundle (byte-identical copies).
RELEASE_ARTIFACT_PATHS = {
    '01_source_manifest.json': 'manifests/sources.json',
    '04_book_master_fa.json': 'master/book.json',
    '06_book_fa.pdf': 'release/06_book_fa.pdf',
    '09_glossary.json': 'release/09_glossary.json',
    '12_source_mapping.json': 'master/source_map.json',
    '13_citation_registry.json': 'provenance/citation-registry.json',
    '14_rag_corpus_fa.jsonl': 'release/14_rag_corpus_fa.jsonl',
    '15_knowledge_graph.json': 'knowledge/graph.json',
    '17_bibliography.json': 'master/bibliography.json',
    '20_content_ids.json': 'provenance/content_ids.json',
}

# ---------------------------------------------------------------- grammar
EDITION_RE = re.compile(r'^\d{4}E\d+$')
CODE_RE = re.compile(r'^[A-Z0-9]{1,8}$')
STRUCTURAL_RE = re.compile(r'^KDJ-([A-Z0-9]{1,8})-(\d{4}E\d+)-P(\d{2})-C(\d{2})-S(\d{2})$')
CONTENT_RE = re.compile(r'^(KDJ-[A-Z0-9]{1,8}-\d{4}E\d+-P\d{2}-C\d{2}-S\d{2})-([A-F0-9]{8})$')
BOOK_SLUG_RE = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')            # registry slug, <= 40
PATH_SLUG_RE = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*-?$')           # part/chapter slug, <= 80
HEX64_RE = re.compile(r'^[0-9a-f]{64}$')
DOC_KEY_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$')
DOC_TITLE_KEY_RE = re.compile(r'^[A-Z0-9][A-Z0-9-]{0,79}$')
ORIGINS = {'source_translation', 'editorial_synthesis', 'editorial_localization_ir'}
CHAPTER_KINDS = {'source', 'reading_guide', 'comparative_synthesis', 'executive', 'localization_ir'}
RESERVED_PART_SLUGS = {'read', 'search', 'glossary', 'sources', 'templates', 'concepts', 'graph', 'ask',
                       'pdf', 'request-pdf', 'news'}
OVERLAY_SCHEMA = 'kbk-reader-overlay/1'
HASH_SPEC = 'kdj-hash-1'
LEGACY_SLUG = 'ai-governance'  # its signed 2026E1 bundle uses /fa/ai-book/ canonical URLs

BOOK_FIELDS = {  # top level: field -> allowed types (None = JSON null)
    'edition_id': (str,), 'locale': (str,), 'title_fa': (str,), 'title_en': (str,), 'compiler': (str,),
    'website': (str,), 'attribution': (str,), 'hash_spec': (str,), 'built_at': (str,), 'parts': (list,),
    'merkle_root': (str,), 'units': (int,),
}
PART_FIELDS = {'part_id': (str,), 'slug': (str,), 'title_fa': (str,), 'title_en': (str,), 'sources': (list,),
               'chapters': (list,), 'part_hash': (str,)}
CHAPTER_FIELDS = {'chapter_id': (str,), 'slug': (str,), 'origin': (str,), 'kind': (str,), 'title_fa': (str,),
                  'title_en': (str,), 'source_doc': (str, type(None)), 'sections': (list,), 'chapter_hash': (str,)}
SECTION_FIELDS = {
    'content_id': (str,), 'structural_id': (str,), 'citation_id': (str,), 'locale': (str,), 'concept_ids': (list,),
    'part_id': (str,), 'chapter_id': (str,), 'section_id': (str,), 'title_fa': (str,), 'title_en': (str,),
    'origin': (str,), 'label_fa': (str, type(None)), 'fa_text': (str,), 'source_documents': (list,),
    'source_blocks': (list,), 'source_pages': (list,), 'source_section': (str, type(None)),
    'derived_from_content_ids': (list,), 'references': (list,), 'tables': (list,), 'figures': (list,),
    'canonical_url': (str,), 'content_hash': (str,), 'chunk_ids': (list,), 'translator_models': (list,),
    'escalated': (bool,),
}
MANIFEST_REQUIRED = ['edition_id', 'build_date', 'publisher', 'merkle_root', 'artifacts', 'missing_deliverables',
                     'hash_spec', 'master_json_sha256', 'release_id', 'compiler', 'website']
MANIFEST_RECOMMENDED = ['master_md_sha256', 'model_routing_summary', 'prompt_versions', 'source_hashes',
                        'tool_versions']

# ---------------------------------------------------------------- kdj-hash-1
_ZW_REMOVE = re.compile('[​‍﻿⁠‎‏‪-‮⁦-⁩]')
_INTRA_WS = re.compile('[ \t ]+')


def canonical_text(s: str) -> str:
    """kdj-hash-1 normalisation (ZWNJ U+200C is kept)."""
    s = unicodedata.normalize('NFC', s or '').replace('\r\n', '\n').replace('\r', '\n')
    s = _ZW_REMOVE.sub('', s)
    s = '\n'.join(_INTRA_WS.sub(' ', line).rstrip() for line in s.split('\n'))
    return re.sub(r'\n{3,}', '\n\n', s).strip('\n')


def content_hash(section: dict) -> str:
    payload = '\n'.join([section['structural_id'], section['locale'], section['origin'],
                         canonical_text(section['title_fa']), canonical_text(section['title_en']),
                         canonical_text(section['fa_text'])])
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()


def merkle(hashes_hex: list) -> str:
    def h(b: bytes) -> str:
        return hashlib.sha256(b).hexdigest()
    if not hashes_hex:
        return h(b'\x00')
    level = [h(b'\x00' + bytes.fromhex(x)) for x in hashes_hex]
    while len(level) > 1:
        level = [h(b'\x01' + bytes.fromhex(level[i]) + bytes.fromhex(level[i + 1])) if i + 1 < len(level) else level[i]
                 for i in range(0, len(level), 2)]
    return level[0]


# ---------------------------------------------------------------- reader Markdown model
_DIGITS = str.maketrans('۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩', '01234567890123456789')
_FN_DEF = re.compile(r'^\s*\[\^([^\]]*)\]:\s*(.*)$')
_FN_REF = re.compile(r'\[\^([^\]]*)\]')
_FN_LEGACY = re.compile(r'(?:^|\s)>\s*([0-9۰-۹]{1,3})(?![0-9۰-۹])\s*')
_TABLE_START = re.compile(r'^\|.*\|$')
_TABLE_LINE = re.compile(r'^\s*\|.*\|\s*$')
_HEADING = re.compile(r'^(#{1,6})\s+(.+)$')
_FIGURE = re.compile(r'\[FIGURE\b', re.I)
_FIGURE_LINE = re.compile(r'^\[FIGURE\b', re.I)
# http(s) links render as anchors (BOOK-FORMAT §6); images and other schemes print literally.
_LINK = re.compile(r'!\[[^\]]*\]\([^)\s]+\)|\[[^\]^][^\]]*\]\((?!https?://)[^)\s]+\)')
_HTML = re.compile(r'</?[A-Za-z][A-Za-z0-9]*(?:\s[^<>]*)?/?>')


def footnote_numbers(label: str) -> list:
    pieces = re.split(r'[\s,،]+', label.translate(_DIGITS).strip())
    if not all(re.fullmatch(r'[0-9]{1,4}', p) for p in pieces):
        return []
    return [str(int(p)) for p in pieces]


def reader_document(text: str) -> dict:
    """Mirror of KBK_AI_Book::reader_document(): body lines, notes, refs."""
    lines, notes, loose = [], set(), 0
    for line in re.split(r'\r\n|\r|\n', text):
        m = _FN_DEF.match(line)
        if not m:
            lines.append(line)
            continue
        label, body = m.group(1).translate(_DIGITS).strip(), m.group(2).strip()
        if re.fullmatch(r'[0-9]{1,4}', label):
            if body:
                notes.add(str(int(label)))
            continue
        pieces = _FN_LEGACY.split(' ' + body)
        for i in range(1, len(pieces) - 1, 2):
            if pieces[i + 1].strip():
                notes.add(str(int(pieces[i].translate(_DIGITS))))
        loose += 1
    refs, orphan_labels = set(), 0
    for line in lines:
        for label in _FN_REF.findall(line):
            numbers = footnote_numbers(label)
            refs.update(numbers)
            orphan_labels += 0 if numbers else 1
    return {'lines': lines, 'notes': notes, 'refs': refs, 'orphan_labels': orphan_labels}


def split_table_row(line: str) -> list:
    line = line.strip()
    if line.startswith('|'):
        line = line[1:]
    if line.endswith('|') and not line.endswith('\\|'):
        line = line[:-1]
    return [c.strip() for c in re.split(r'(?<!\\)\|', line)]


def tables_of(lines: list) -> list:
    out, i = [], 0
    while i < len(lines):
        if _TABLE_START.match(lines[i].strip()):
            rows = []
            while i < len(lines) and _TABLE_LINE.match(lines[i]):
                rows.append(split_table_row(lines[i]))
                i += 1
            out.append(rows)
            continue
        i += 1
    return out


# ---------------------------------------------------------------- reporting
class Check:
    def __init__(self, name: str):
        self.name, self.fails, self.warns, self.checked, self.notes, self.skipped = name, [], [], 0, [], None

    def fail(self, msg: str) -> None:
        self.fails.append(msg)

    def warn(self, msg: str) -> None:
        self.warns.append(msg)

    def skip(self, why: str) -> 'Check':
        self.skipped = why
        return self

    @property
    def status(self) -> str:
        if self.skipped:
            return 'SKIP'
        return 'FAIL' if self.fails else 'WARN' if self.warns else 'PASS'

    def as_dict(self) -> dict:
        problems = self.fails or self.warns
        return {'name': self.name, 'status': self.status,
                'count': len(problems) if problems else self.checked,
                'examples': (self.fails + self.warns)[:3],
                'detail': self.skipped or '; '.join(self.notes)}


class Ctx:
    def __init__(self, root: Path, strict: bool, require_build: bool, slug, code):
        self.root, self.strict, self.require_build, self.slug, self.code = root, strict, require_build, slug, code
        self.data, self.raw_book, self.templates = {}, None, {}
        self.sections, self.chapters = [], []          # [(part, chapter, section)], [(part, chapter)]
        self.by_sid, self.by_cid = {}, {}
        self.doc_keys = set()
        self.overlay_applies = False
        self.edition = None


def is_type(value, types) -> bool:
    if bool in types or not isinstance(value, bool):
        return isinstance(value, types)
    return False


def non_empty(value) -> bool:
    return isinstance(value, str) and value.strip() != ''


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for block in iter(lambda: fh.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def url_ok(url, ctx: Ctx, part_slug=None, chapter_slug=None, fragment=None) -> bool:
    """https://kohandezh.com/fa/books/{slug}/{part}/{chapter}/#{sid} (legacy: /fa/ai-book/…)."""
    if not isinstance(url, str):
        return False
    u = urlsplit(url)
    if u.scheme != 'https' or u.netloc != 'kohandezh.com' or (fragment is not None and u.fragment != fragment):
        return False
    prefixes = ['/fa/books/%s/' % ctx.slug]
    if ctx.slug == LEGACY_SLUG:
        prefixes.append('/fa/ai-book/')
    if part_slug is None:
        return any(u.path.startswith(p) for p in prefixes)
    return u.path in ['%s%s/%s/' % (p, part_slug, chapter_slug) for p in prefixes]


# ---------------------------------------------------------------- checks
def check_files(ctx: Ctx) -> Check:
    c = Check('files')
    root = ctx.root
    tpls = sorted(root.glob(TEMPLATE_GLOB))
    groups = [(REQUIRED_FILES, 'required'), (BUILD_FILES, 'build'), (OPTIONAL_FILES, 'optional')]
    for files, kind in groups:
        for rel in files:
            p = root / rel
            if not p.is_file():
                if kind == 'required' or ctx.strict or (kind == 'build' and ctx.require_build):
                    c.fail('missing %s file %s' % (kind, rel))
                elif kind == 'build':
                    c.warn('build output %s absent (gitignored in the repo; required in the upload)' % rel)
                else:
                    c.notes.append('optional %s absent' % rel)
                continue
            c.checked += 1
            try:
                if rel.endswith('.pdf'):
                    with open(p, 'rb') as fh:
                        if fh.read(5) != b'%PDF-':
                            c.fail('%s has no %%PDF- header' % rel)
                    continue
                if rel.endswith('.jsonl'):
                    rows = []
                    with open(p, encoding='utf-8') as fh:
                        for n, line in enumerate(fh, 1):
                            if line.strip():
                                obj = json.loads(line)
                                if not isinstance(obj, dict):
                                    raise ValueError('line %d is not an object' % n)
                                rows.append(obj)
                    ctx.data[rel] = rows
                    continue
                raw = p.read_bytes()
                if rel == 'master/book.json':
                    ctx.raw_book = raw
                ctx.data[rel] = json.loads(raw.decode('utf-8'))
                expect = list if rel == 'master/source_map.json' else dict
                if not isinstance(ctx.data[rel], expect):
                    c.fail('%s top level must be a JSON %s' % (rel, 'array' if expect is list else 'object'))
                    ctx.data.pop(rel)
            except (ValueError, UnicodeDecodeError) as e:
                c.fail('%s does not parse: %s' % (rel, str(e)[:80]))
                ctx.data.pop(rel, None)
    if not tpls:
        c.fail('no %s template files' % TEMPLATE_GLOB)
    for p in tpls:
        c.checked += 1
        try:
            obj = json.loads(p.read_text(encoding='utf-8'))
            if not isinstance(obj, dict):
                raise ValueError('not an object')
            ctx.templates[p.stem] = obj
        except ValueError as e:
            c.fail('templates/%s does not parse: %s' % (p.name, str(e)[:80]))
    c.notes.append('%d files parsed, %d templates' % (c.checked - len(tpls), len(tpls)))
    return c


def check_book_top(ctx: Ctx) -> Check:
    c = Check('book.top_level')
    book = ctx.data.get('master/book.json')
    if not isinstance(book, dict):
        return c.skip('book.json not loaded')
    for field, types in BOOK_FIELDS.items():
        c.checked += 1
        if field not in book:
            c.fail('book.%s missing' % field)
        elif not is_type(book[field], types):
            c.fail('book.%s must be %s' % (field, '/'.join(t.__name__ for t in types)))
    if c.fails:
        return c
    if not EDITION_RE.match(book['edition_id']):
        c.fail('edition_id %r is not \\d{4}E\\d+' % book['edition_id'])
    else:
        ctx.edition = book['edition_id']
    if book['locale'] != 'fa':
        c.fail('locale must be "fa"')
    for f in ('title_fa', 'compiler', 'attribution', 'built_at'):
        if not non_empty(book[f]):
            c.fail('book.%s must be a non-empty string' % f)
    if book['hash_spec'] != HASH_SPEC:
        c.fail('hash_spec %r is not %s (the only spec this validator knows)' % (book['hash_spec'], HASH_SPEC))
    if not HEX64_RE.match(book['merkle_root']):
        c.fail('merkle_root is not 64 lowercase hex')
    if not book['parts']:
        c.fail('parts is empty')
    if 'coverage' in book and not isinstance(book['coverage'], dict):
        c.fail('coverage must be an object when present')
    if book['units'] < 1:
        c.fail('units must be a positive integer')
    return c


def check_book_structure(ctx: Ctx) -> Check:
    c = Check('book.structure')
    book = ctx.data.get('master/book.json')
    if not isinstance(book, dict) or not isinstance(book.get('parts'), list):
        return c.skip('book.json parts not loaded')
    chapter_no, seen_chapters = 0, set()
    for pi, part in enumerate(book['parts'], 1):
        if not isinstance(part, dict):
            c.fail('parts[%d] is not an object' % (pi - 1))
            continue
        for field, types in PART_FIELDS.items():
            if field not in part or not is_type(part[field], types):
                c.fail('part %s.%s missing or not %s' % (part.get('part_id', pi), field, types[0].__name__))
        if part.get('part_id') != 'P%02d' % pi:
            c.fail('parts[%d].part_id %r != P%02d (position)' % (pi - 1, part.get('part_id'), pi))
        slug = part.get('slug')
        if not isinstance(slug, str) or not PATH_SLUG_RE.match(slug) or len(slug) > 80:
            c.fail('part %s slug %r breaks the slug grammar' % (part.get('part_id'), slug))
        elif slug in RESERVED_PART_SLUGS:
            c.fail('part %s slug %r is a reserved view name' % (part.get('part_id'), slug))
        if not non_empty(part.get('title_fa')):
            c.fail('part %s title_fa empty' % part.get('part_id'))
        if isinstance(part.get('part_hash'), str) and not HEX64_RE.match(part['part_hash']):
            c.fail('part %s part_hash is not 64 hex' % part.get('part_id'))
        chapters = part.get('chapters') if isinstance(part.get('chapters'), list) else []
        if not chapters:
            c.fail('part %s has no chapters' % part.get('part_id'))
        slugs: dict = {}
        for chapter in chapters:
            chapter_no += 1
            c.checked += 1
            if not isinstance(chapter, dict):
                c.fail('a chapter of %s is not an object' % part.get('part_id'))
                continue
            cid = chapter.get('chapter_id')
            for field, types in CHAPTER_FIELDS.items():
                if field not in chapter or not is_type(chapter[field], types):
                    c.fail('chapter %s.%s missing or not %s' % (cid, field, '/'.join(t.__name__ for t in types)))
            if cid != 'C%02d' % chapter_no:
                c.fail('chapter %r != C%02d (chapters are numbered book-wide)' % (cid, chapter_no))
            if cid in seen_chapters:
                c.fail('chapter_id %s repeats' % cid)
            seen_chapters.add(cid)
            cslug = chapter.get('slug')
            if not isinstance(cslug, str) or not PATH_SLUG_RE.match(cslug) or len(cslug) > 80:
                c.fail('chapter %s slug %r breaks the slug grammar' % (cid, cslug))
            else:
                slugs.setdefault(cslug, []).append(cid)
            if chapter.get('origin') not in ORIGINS:
                c.fail('chapter %s origin %r not allowed' % (cid, chapter.get('origin')))
            if isinstance(chapter.get('kind'), str) and chapter['kind'] not in CHAPTER_KINDS:
                c.warn('chapter %s kind %r is not one of %s' % (cid, chapter['kind'], sorted(CHAPTER_KINDS)))
            if not non_empty(chapter.get('title_fa')):
                c.fail('chapter %s title_fa empty' % cid)
            if isinstance(chapter.get('chapter_hash'), str) and not HEX64_RE.match(chapter['chapter_hash']):
                c.fail('chapter %s chapter_hash is not 64 hex' % cid)
            sections = chapter.get('sections') if isinstance(chapter.get('sections'), list) else []
            if not sections:
                c.fail('chapter %s has no sections' % cid)
            if len(sections) > 99:
                c.fail('chapter %s has %d sections (max 99)' % (cid, len(sections)))
            ctx.chapters.append((part, chapter))
            for si, section in enumerate(sections, 1):
                if not isinstance(section, dict):
                    c.fail('%s section %d is not an object' % (cid, si))
                    continue
                if section.get('section_id') != 'S%02d' % si:
                    c.fail('%s sections[%d].section_id %r != S%02d' % (cid, si - 1, section.get('section_id'), si))
                ctx.sections.append((part, chapter, section))
        for cslug, ids in slugs.items():
            if len(ids) > 1:
                c.warn('chapter slug %r is shared by %s in %s: their canonical_url path cannot be resolved'
                       % (cslug, ', '.join(ids), part.get('part_id')))
    if len(book['parts']) > 99 or chapter_no > 99:
        c.fail('%d parts / %d chapters exceed the two-digit limit (99)' % (len(book['parts']), chapter_no))
    if isinstance(book.get('units'), int) and book['units'] != len(ctx.sections):
        c.fail('units=%s but the book holds %d sections' % (book['units'], len(ctx.sections)))
    c.notes.append('%d parts, %d chapters, %d sections' % (len(book['parts']), chapter_no, len(ctx.sections)))
    return c


def check_section_fields(ctx: Ctx) -> Check:
    c = Check('book.section_fields')
    if not ctx.sections:
        return c.skip('no sections loaded')
    for part, chapter, s in ctx.sections:
        c.checked += 1
        sid = s.get('structural_id', '?')
        for field, types in SECTION_FIELDS.items():
            if field not in s:
                c.fail('%s.%s missing' % (sid, field))
            elif not is_type(s[field], types):
                c.fail('%s.%s must be %s' % (sid, field, '/'.join(t.__name__ for t in types)))
        if s.get('locale') != 'fa':
            c.fail('%s.locale must be "fa"' % sid)
        if s.get('origin') not in ORIGINS:
            c.fail('%s.origin %r not allowed' % (sid, s.get('origin')))
        for f in ('title_fa', 'fa_text'):
            if f in s and not non_empty(s[f]):
                c.fail('%s.%s is empty' % (sid, f))
        if s.get('part_id') != part.get('part_id') or s.get('chapter_id') != chapter.get('chapter_id'):
            c.fail('%s part_id/chapter_id disagree with its position' % sid)
        docs = s.get('source_documents')
        if isinstance(docs, list):
            if not all(isinstance(d, str) for d in docs):
                c.fail('%s.source_documents must hold strings' % sid)
            elif ctx.doc_keys and any(d not in ctx.doc_keys for d in docs):
                c.warn('%s cites a document missing from manifests/sources.json' % sid)
    return c


def check_ids(ctx: Ctx) -> Check:
    c = Check('ids.grammar')
    if not ctx.sections:
        return c.skip('no sections loaded')
    codes = set()
    for part, chapter, s in ctx.sections:
        c.checked += 1
        sid, cid = s.get('structural_id'), s.get('content_id')
        m = STRUCTURAL_RE.match(sid) if isinstance(sid, str) else None
        if not m:
            c.fail('structural_id %r breaks KDJ-{CODE}-{EDITION}-Pnn-Cnn-Snn' % sid)
            continue
        codes.add(m.group(1))
        expect = 'KDJ-%s-%s-%s-%s-%s' % (m.group(1), ctx.edition, part.get('part_id'), chapter.get('chapter_id'),
                                         s.get('section_id'))
        if sid != expect:
            c.fail('structural_id %s != %s (edition/position)' % (sid, expect))
        if s.get('citation_id') != sid:
            c.fail('%s citation_id %r != structural_id' % (sid, s.get('citation_id')))
        cm = CONTENT_RE.match(cid) if isinstance(cid, str) else None
        if not cm or cm.group(1) != sid:
            c.fail('content_id %r is not structural_id + "-" + HASH8' % cid)
        else:
            ch = s.get('content_hash', '')
            if isinstance(ch, str) and ch.startswith('sha256:') and HEX64_RE.match(ch[7:]):
                if cm.group(2) != ch[7:15].upper():
                    c.fail('%s HASH8 %s != content_hash[:8] %s' % (sid, cm.group(2), ch[7:15].upper()))
            else:
                c.fail('%s content_hash %r is not "sha256:" + 64 hex' % (sid, ch))
        if sid in ctx.by_sid:
            c.fail('structural_id %s repeats' % sid)
        if cid in ctx.by_cid:
            c.fail('content_id %s repeats' % cid)
        ctx.by_sid[sid], ctx.by_cid[cid] = s, s
        if not url_ok(s.get('canonical_url'), ctx, part.get('slug'), chapter.get('slug'), sid):
            c.fail('%s canonical_url %r is not https://kohandezh.com/fa/books/%s/{part_slug}/{chapter_slug}/#%s'
                   % (sid, s.get('canonical_url'), ctx.slug, sid))
    if len(codes) > 1:
        c.fail('more than one ID code in one book: %s' % sorted(codes))
    if ctx.code and codes and codes != {ctx.code}:
        c.fail('ID code %s != expected %s' % (sorted(codes), ctx.code))
    c.notes.append('code %s, slug %s' % ('/'.join(sorted(codes)) or '?', ctx.slug))
    return c


def check_content_hashes(ctx: Ctx) -> Check:
    c = Check('ids.content_hash')
    book = ctx.data.get('master/book.json') or {}
    if not ctx.sections or book.get('hash_spec') != HASH_SPEC:
        return c.skip('no sections, or hash_spec is not %s' % HASH_SPEC)
    for _, _, s in ctx.sections:
        if not all(isinstance(s.get(f), str) for f in ('structural_id', 'locale', 'origin', 'title_fa', 'title_en',
                                                         'fa_text', 'content_hash')):
            continue
        c.checked += 1
        got = content_hash(s)
        if s['content_hash'] != 'sha256:' + got:
            c.fail('%s text does not hash to its content_hash (got %s…, stored %s…)'
                   % (s['structural_id'], got[:12], s['content_hash'][7:19]))
    c.notes.append('%d sections re-hashed (kdj-hash-1)' % c.checked)
    return c


def check_merkle(ctx: Ctx) -> Check:
    c = Check('ids.merkle')
    book = ctx.data.get('master/book.json')
    if not ctx.sections or not isinstance(book, dict):
        return c.skip('no sections loaded')
    part_hashes = []
    try:
        for part in book['parts']:
            chapter_hashes = []
            for chapter in part['chapters']:
                root = merkle([s['content_hash'].split(':', 1)[1] for s in chapter['sections']])
                c.checked += 1
                if root != chapter.get('chapter_hash'):
                    c.fail('%s chapter_hash does not match its sections' % chapter.get('chapter_id'))
                chapter_hashes.append(root)
            root = merkle(chapter_hashes)
            if root != part.get('part_hash'):
                c.fail('%s part_hash does not match its chapters' % part.get('part_id'))
            part_hashes.append(root)
        if merkle(part_hashes) != book.get('merkle_root'):
            c.fail('merkle_root does not match the parts')
    except (KeyError, TypeError, ValueError, AttributeError) as e:
        c.fail('tree is not hashable: %s' % e)
    return c


def check_content_ids_registry(ctx: Ctx) -> Check:
    c = Check('provenance.content_ids')
    reg = ctx.data.get('provenance/content_ids.json')
    if not isinstance(reg, dict) or not ctx.by_cid:
        return c.skip('content_ids.json or sections not loaded')
    ids = reg.get('ids')
    if not isinstance(ids, dict) or reg.get('count') != len(ids if isinstance(ids, dict) else []):
        c.fail('count must equal the number of ids')
        if not isinstance(ids, dict):
            return c
    if len(ids) != len(ctx.by_cid):
        c.fail('%d ids registered, book has %d sections' % (len(ids), len(ctx.by_cid)))
    for cid in sorted(set(ctx.by_cid) - set(ids))[:50]:
        c.fail('book content_id %s not registered' % cid)
    for cid, e in ids.items():
        c.checked += 1
        s = ctx.by_cid.get(cid)
        if s is None:
            c.fail('registered id %s is not in book.json' % cid)
            continue
        want = {'structural_id': s.get('structural_id'), 'part': s.get('part_id'), 'chapter': s.get('chapter_id'),
                'section': s.get('section_id'), 'origin': s.get('origin'), 'locale': 'fa',
                'hash': str(s.get('content_hash', ''))[7:]}
        bad = [k for k, v in want.items() if not isinstance(e, dict) or e.get(k) != v]
        if bad:
            c.fail('%s disagrees with book.json on %s' % (cid, ', '.join(bad)))
    return c


def check_citation_registry(ctx: Ctx) -> Check:
    c = Check('provenance.citations')
    reg = ctx.data.get('provenance/citation-registry.json')
    if not isinstance(reg, dict) or not ctx.by_sid:
        return c.skip('citation-registry.json or sections not loaded')
    entries = reg.get('registry')
    if not isinstance(entries, dict) or reg.get('count') != len(entries if isinstance(entries, dict) else []):
        c.fail('count must equal the number of registry entries')
        if not isinstance(entries, dict):
            return c
    for sid in sorted(set(ctx.by_sid) - set(entries))[:50]:
        c.fail('section %s has no citation entry' % sid)
    for sid, e in entries.items():
        c.checked += 1
        s = ctx.by_sid.get(sid)
        if s is None or not isinstance(e, dict):
            c.fail('citation key %s is not a section of book.json' % sid)
            continue
        for k in ('content_id', 'origin', 'canonical_url'):
            if e.get(k) != s.get(k):
                c.fail('%s citation %s disagrees with book.json' % (sid, k))
        if not non_empty(e.get('title_fa')) or not non_empty(e.get('citation_fa')):
            c.fail('%s citation title_fa/citation_fa empty' % sid)
        if not isinstance(e.get('source_documents'), list):
            c.fail('%s citation source_documents is not a list' % sid)
    return c


def check_editions(ctx: Ctx) -> Check:
    c = Check('edition.consistency')
    if not ctx.edition:
        return c.skip('book edition_id not valid')
    probes = [('provenance/content_ids.json', 'edition_id'), ('provenance/citation-registry.json', 'edition_id'),
              ('provenance/release-manifest.json', 'edition_id'), ('master/reader-overlay.json', 'edition_id'),
              ('html/search/index.json', 'edition'), ('knowledge/graph.json', 'edition')]
    for rel, key in probes:
        obj = ctx.data.get(rel)
        if isinstance(obj, dict):
            c.checked += 1
            if obj.get(key) != ctx.edition:
                c.fail('%s %s=%r != book %s' % (rel, key, obj.get(key), ctx.edition))
    rag = ctx.data.get('release/14_rag_corpus_fa.jsonl') or []
    other = sum(1 for r in rag if ('-%s-' % ctx.edition) not in str(r.get('content_id', '')))
    if other:
        c.fail('%d RAG chunks carry another edition' % other)
    c.notes.append('edition %s; %d artifacts + RAG ids compared' % (ctx.edition, c.checked))
    return c


def check_release_manifest(ctx: Ctx) -> Check:
    c = Check('provenance.release_manifest')
    man = ctx.data.get('provenance/release-manifest.json')
    book = ctx.data.get('master/book.json')
    if not isinstance(man, dict) or not isinstance(book, dict):
        return c.skip('release-manifest.json or book.json not loaded')
    for k in MANIFEST_REQUIRED:
        c.checked += 1
        if k not in man:
            c.fail('release-manifest.%s missing' % k)
    for k in MANIFEST_RECOMMENDED:
        if k not in man:
            c.warn('release-manifest.%s missing (pipeline provenance)' % k)
    if c.fails:
        return c
    if not non_empty(man['build_date']) or len(man['build_date']) > 32:
        c.fail('build_date must be a non-empty string <= 32 chars')
    if not non_empty(man['publisher']) or len(man['publisher']) > 120:
        c.fail('publisher must be a non-empty string <= 120 chars')
    if man['hash_spec'] != book.get('hash_spec'):
        c.fail('hash_spec %r != book %r' % (man['hash_spec'], book.get('hash_spec')))
    if man['merkle_root'] != book.get('merkle_root'):
        c.fail('merkle_root differs from book.json')
    arts = man['artifacts']
    if not isinstance(arts, dict) or not 1 <= len(arts) <= 32:
        c.fail('artifacts must be an object of 1..32 entries')
        return c
    if '06_book_fa.pdf' not in arts:
        c.fail('artifacts must list 06_book_fa.pdf')
    for name, a in arts.items():
        if not isinstance(a, dict) or not isinstance(a.get('bytes'), int) or not HEX64_RE.match(str(a.get('sha256'))):
            c.fail('artifacts.%s needs {bytes:int, sha256:64 hex}' % name)
    md = man['missing_deliverables']
    if not isinstance(md, list) or len(md) > 50 or not all(isinstance(x, str) and len(x) <= 200 for x in md):
        c.fail('missing_deliverables must be a list of <= 50 short strings')
    if ctx.raw_book is not None:
        actual = hashlib.sha256(ctx.raw_book).hexdigest()
        if man['master_json_sha256'] != actual:
            c.warn('master_json_sha256 != sha256(book.json): book.json is not the signed bytes '
                   '(edited or reformatted); the overlay and verification depend on them')
        else:
            c.notes.append('book.json is byte-identical to the signed master')
    for name, rel in RELEASE_ARTIFACT_PATHS.items():
        a, p = arts.get(name), ctx.root / rel
        if not isinstance(a, dict) or not p.is_file() or rel.endswith('.pdf'):
            continue  # the PDF is checked by pdf.file
        c.checked += 1
        if p.stat().st_size != a.get('bytes') or sha256_file(p) != a.get('sha256'):
            c.warn('%s is not byte-identical to release artifact %s' % (rel, name))
    return c


def check_overlay(ctx: Ctx) -> Check:
    c = Check('overlay')
    ov = ctx.data.get('master/reader-overlay.json')
    if ov is None:
        return c.skip('no master/reader-overlay.json (canonical text is rendered)')
    if not ctx.by_sid:
        return c.skip('sections not loaded')
    if ov.get('schema') != OVERLAY_SCHEMA:
        c.fail('schema %r != %s' % (ov.get('schema'), OVERLAY_SCHEMA))
    if ov.get('edition_id') != ctx.edition:
        c.fail('edition_id %r != book %s' % (ov.get('edition_id'), ctx.edition))
    actual = hashlib.sha256(ctx.raw_book or b'').hexdigest()
    if ov.get('book_sha256') != actual:
        c.fail('book_sha256 is stale (overlay %s…, book.json %s…): the reader ignores the whole overlay'
               % (str(ov.get('book_sha256'))[:12], actual[:12]))
    if not non_empty(ov.get('generator')):
        c.warn('generator is missing')
    ctx.overlay_applies = not c.fails
    chapter_ids = {ch.get('chapter_id') for _, ch in ctx.chapters}
    chapters = ov.get('chapters', {})
    if not isinstance(chapters, dict):
        c.fail('chapters must be an object')
        chapters = {}
    for key, patch in chapters.items():
        c.checked += 1
        if key not in chapter_ids:
            c.fail('chapters.%s is not a chapter of the book' % key)
        elif not isinstance(patch, dict) or not non_empty(patch.get('title_fa')) or set(patch) - {'title_fa'}:
            c.fail('chapters.%s must be {title_fa: non-empty string}' % key)
    sections = ov.get('sections', {})
    if not isinstance(sections, dict):
        c.fail('sections must be an object')
        sections = {}
    unmatched = 0
    for key, patch in sections.items():
        c.checked += 1
        if key not in ctx.by_sid:
            c.fail('sections.%s is not a structural_id of the book' % key)
            continue
        if not isinstance(patch, dict) or not patch or set(patch) - {'title_fa', 'fa_text', 'omit'}:
            c.fail('sections.%s must hold only title_fa / fa_text / omit' % key)
            continue
        for f in ('title_fa', 'fa_text'):
            if f in patch and not non_empty(patch[f]):
                c.fail('sections.%s.%s must be a non-empty string' % (key, f))
        if 'omit' in patch and patch['omit'] is not True:
            c.fail('sections.%s.omit must be true when present' % key)
        if isinstance(patch.get('fa_text'), str):
            doc = reader_document(patch['fa_text'])
            missing = sorted(doc['refs'] - doc['notes'], key=int)
            if missing:
                unmatched += len(missing)
                c.warn('sections.%s fa_text references [^%s] with no definition' % (key, ','.join(missing[:5])))
    c.notes.append('%d chapter + %d section patches; applies=%s; %d unmatched footnote refs'
                   % (len(chapters), len(sections), ctx.overlay_applies, unmatched))
    return c


def rendered_sections(ctx: Ctx):
    """(structural_id, text) exactly as the reader shows it: overlay applied when valid, omitted skipped."""
    patches = (ctx.data.get('master/reader-overlay.json') or {}).get('sections', {}) if ctx.overlay_applies else {}
    for _, _, s in ctx.sections:
        patch = patches.get(s.get('structural_id')) if isinstance(patches, dict) else None
        patch = patch if isinstance(patch, dict) else {}
        if patch.get('omit') is True:
            continue
        text = patch.get('fa_text') if non_empty(patch.get('fa_text')) else s.get('fa_text')
        if isinstance(text, str):
            yield s.get('structural_id'), text


def check_markdown_tables(ctx: Ctx) -> Check:
    c = Check('markdown.tables')
    if not ctx.sections:
        return c.skip('no sections loaded')
    for sid, text in rendered_sections(ctx):
        for rows in tables_of(reader_document(text)['lines']):
            c.checked += 1
            widths = sorted({len(r) for r in rows})
            if len(widths) > 1:
                c.warn('%s: ragged table (row widths %s); the reader pads short rows' % (sid, widths))
    c.notes.append('%d tables (overlay %s)' % (c.checked, 'applied' if ctx.overlay_applies else 'not applied'))
    return c


def check_markdown_footnotes(ctx: Ctx) -> Check:
    c = Check('markdown.footnotes')
    if not ctx.sections:
        return c.skip('no sections loaded')
    for sid, text in rendered_sections(ctx):
        doc = reader_document(text)
        c.checked += len(doc['refs'])
        missing = sorted(doc['refs'] - doc['notes'], key=int)
        if missing:
            c.warn('%s: [^%s] has no [^n]: definition; the reader drops the mark' % (sid, ','.join(missing[:5])))
        if doc['orphan_labels']:
            c.warn('%s: %d non-numeric footnote labels (dropped)' % (sid, doc['orphan_labels']))
    c.notes.append('%d footnote references' % c.checked)
    return c


def check_markdown_figures(ctx: Ctx) -> Check:
    c = Check('markdown.figures')
    if not ctx.sections:
        return c.skip('no sections loaded')
    own_line = 0
    for sid, text in rendered_sections(ctx):
        for line in reader_document(text)['lines']:
            hits = len(_FIGURE.findall(line))
            if not hits:
                continue
            c.checked += hits
            if _FIGURE_LINE.match(line.strip()) and hits == 1:
                own_line += 1
            else:
                c.warn('%s: [FIGURE …] inside running text or a table is dropped silently' % sid)
    c.notes.append('%d [FIGURE …] markers; %d on their own line become figure notes or are hidden'
                   % (c.checked, own_line))
    return c


def check_markdown_unsupported(ctx: Ctx) -> Check:
    c = Check('markdown.unsupported')
    if not ctx.sections:
        return c.skip('no sections loaded')
    for sid, text in rendered_sections(ctx):
        c.checked += 1
        for line in reader_document(text)['lines']:
            t = line.strip()
            for m in _LINK.findall(t):
                c.warn('%s: link/image %s prints as literal text' % (sid, m[:60]))
            for m in _HTML.findall(t):
                c.warn('%s: raw HTML %s is escaped and printed' % (sid, m[:40]))
            if re.match(r'^#{7,}\s', t):
                c.warn('%s: heading deeper than ###### renders as a paragraph' % sid)
    return c


def check_doc_titles(ctx: Ctx) -> Check:
    c = Check('taxonomy.doc_titles')
    dt = ctx.data.get('taxonomy/doc_titles_fa.json')
    if dt is None:
        return c.skip('no taxonomy/doc_titles_fa.json (source titles are shown)')
    for key, e in dt.items():
        c.checked += 1
        if not DOC_TITLE_KEY_RE.match(key):
            c.fail('key %r is not [A-Z0-9][A-Z0-9-]{0,79}' % key)
        if not isinstance(e, dict) or not non_empty(e.get('title_fa')) or len(e.get('title_fa', '')) > 300:
            c.fail('%s.title_fa must be a non-empty string <= 300' % key)
        elif 'subtitle_fa' in e and (not isinstance(e['subtitle_fa'], str) or len(e['subtitle_fa']) > 300):
            c.fail('%s.subtitle_fa must be a string <= 300' % key)
        if ctx.doc_keys and key not in ctx.doc_keys:
            c.warn('%s is not a doc_key of manifests/sources.json' % key)
    return c


def check_glossary(ctx: Ctx) -> Check:
    c = Check('release.glossary')
    g = ctx.data.get('release/09_glossary.json')
    if g is None:
        return c.skip('glossary not loaded')
    if not non_empty(g.get('glossary_version')) or not isinstance(g.get('terms'), dict):
        c.fail('needs glossary_version (string) and terms (object)')
        return c
    req = ('concept_id', 'english', 'preferred_fa', 'acronym', 'alternatives_fa', 'definition_fa', 'definition_en',
           'domain', 'status', 'source_documents')
    for key, t in g['terms'].items():
        c.checked += 1
        if not isinstance(t, dict) or any(k not in t for k in req):
            c.fail('term %r lacks one of %s' % (key, ', '.join(req)))
            continue
        if not isinstance(t['concept_id'], str) or not re.match(r'^[A-Za-z][A-Za-z0-9_ ]{0,63}$', t['concept_id']):
            c.fail('term %r concept_id %r is invalid' % (key, t['concept_id']))
        if not non_empty(t['english']) or not non_empty(t['preferred_fa']):
            c.fail('term %r english/preferred_fa empty' % key)
        if not all(isinstance(t[k], str) for k in ('acronym', 'definition_fa', 'definition_en', 'domain', 'status')):
            c.fail('term %r string fields have the wrong type' % key)
        if t['status'] not in ('approved', 'proposed', 'english_only'):
            c.fail('term %r status %r not allowed' % (key, t['status']))
        for k in ('alternatives_fa', 'source_documents'):
            if not isinstance(t[k], list) or not all(isinstance(x, str) for x in t[k]):
                c.fail('term %r %s must be a list of strings' % (key, k))
    return c


def check_sources(ctx: Ctx) -> Check:
    c = Check('manifests.sources+bibliography')
    src = ctx.data.get('manifests/sources.json')
    if not isinstance(src, dict):
        return c.skip('sources.json not loaded')
    docs = src.get('documents')
    if not isinstance(docs, list) or src.get('unique_source_document_count') != len(docs or []) or not docs:
        c.fail('unique_source_document_count must equal len(documents) > 0')
        docs = docs if isinstance(docs, list) else []
    for i, d in enumerate(docs):
        c.checked += 1
        if not isinstance(d, dict) or any(k not in d for k in ('doc_key', 'filename', 'sha256', 'pages', 'title')):
            c.fail('documents[%d] lacks doc_key/filename/sha256/pages/title' % i)
            continue
        if not isinstance(d['doc_key'], str) or not DOC_KEY_RE.match(d['doc_key']) or d['doc_key'] in ctx.doc_keys:
            c.fail('documents[%d].doc_key %r invalid or repeated' % (i, d['doc_key']))
        ctx.doc_keys.add(d['doc_key'])
        if not HEX64_RE.match(str(d['sha256'])) or not isinstance(d['pages'], int) or d['pages'] < 1:
            c.fail('%s sha256/pages invalid' % d['doc_key'])
        if not non_empty(d['filename']) or not non_empty(d['title']):
            c.fail('%s filename/title empty' % d['doc_key'])
    bib = ctx.data.get('master/bibliography.json')
    entries = bib.get('entries') if isinstance(bib, dict) else None
    if not isinstance(entries, list):
        c.fail('bibliography.json needs entries (list)')
        return c
    seen = set()
    for i, e in enumerate(entries):
        c.checked += 1
        req = ('doc_key', 'title', 'organization', 'publication_type', 'publication_status', 'sha256')
        if not isinstance(e, dict) or any(k not in e for k in req):
            c.fail('bibliography[%d] lacks one of %s' % (i, ', '.join(req)))
            continue
        if e['doc_key'] in seen or not DOC_KEY_RE.match(str(e['doc_key'])):
            c.fail('bibliography[%d].doc_key %r invalid or repeated' % (i, e['doc_key']))
        seen.add(e['doc_key'])
        if e['doc_key'] not in ctx.doc_keys:
            c.fail('bibliography %s is missing from manifests/sources.json' % e['doc_key'])
        if not all(non_empty(e[k]) for k in req[1:5]) or not HEX64_RE.match(str(e['sha256'])):
            c.fail('bibliography %s has empty fields or a bad sha256' % e['doc_key'])
    return c


def check_source_map(ctx: Ctx) -> Check:
    c = Check('master.source_map')
    sm = ctx.data.get('master/source_map.json')
    if not isinstance(sm, list):
        return c.skip('source_map.json not loaded')
    for i, e in enumerate(sm):
        c.checked += 1
        if not isinstance(e, dict) or any(k not in e for k in ('content_id', 'structural_id', 'origin', 'source_doc')):
            c.fail('source_map[%d] lacks content_id/structural_id/origin/source_doc' % i)
            continue
        s = ctx.by_sid.get(e['structural_id'])
        if s is None:
            c.fail('source_map[%d] structural_id %s is not a section' % (i, e['structural_id']))
        elif e['content_id'] != s.get('content_id') or e['origin'] != s.get('origin'):
            c.fail('source_map[%d] content_id/origin disagree with %s' % (i, e['structural_id']))
        if ctx.doc_keys and e['source_doc'] not in ctx.doc_keys:
            c.fail('source_map[%d] source_doc %r is not in manifests/sources.json' % (i, e['source_doc']))
    return c


def check_templates(ctx: Ctx) -> Check:
    c = Check('templates')
    if not ctx.templates:
        return c.skip('no templates loaded')
    for stem, t in sorted(ctx.templates.items()):
        c.checked += 1
        if any(k not in t for k in ('template_id', 'title_fa', 'fields', 'origin')):
            c.fail('%s lacks template_id/title_fa/fields/origin' % stem)
            continue
        if not re.match(r'^TPL-P\d{2}-\d{1,2}$', str(t['template_id'])) or t['template_id'] != stem:
            c.fail('%s template_id %r must be TPL-Pnn-n and equal the file name' % (stem, t['template_id']))
        if t['origin'] != 'editorial_template_ir' or not non_empty(t['title_fa']):
            c.fail('%s origin must be editorial_template_ir and title_fa non-empty' % stem)
        if 'note_fa' in t and not isinstance(t['note_fa'], str):
            c.fail('%s note_fa must be a string' % stem)
        if not isinstance(t['fields'], list):
            c.fail('%s fields must be a list' % stem)
            continue
        for j, f in enumerate(t['fields']):
            if not isinstance(f, dict) or not all(non_empty(f.get(k)) for k in ('name_fa', 'name_en', 'description_fa')):
                c.fail('%s fields[%d] needs name_fa/name_en/description_fa' % (stem, j))
            elif 'example_fa' in f and not isinstance(f['example_fa'], str):
                c.fail('%s fields[%d].example_fa must be a string' % (stem, j))
    return c


def _entity_problem(e, ctx: Ctx):
    if not isinstance(e, dict) or any(k not in e for k in ('entity_id', 'type', 'labels', 'origin', 'documents')):
        return 'lacks entity_id/type/labels/origin/documents'
    if not re.match(r'^E:[A-Za-z][A-Za-z0-9]{0,40}:[a-z0-9_-]{1,100}$', str(e['entity_id'])):
        return 'entity_id %r invalid' % e['entity_id']
    if not re.match(r'^[A-Za-z][A-Za-z0-9]{0,40}$', str(e['type'])):
        return '%s type invalid' % e['entity_id']
    if not isinstance(e['labels'], dict) or any(not isinstance(e['labels'].get(k, ''), str) for k in ('en', 'fa')):
        return '%s labels must be {en?, fa?} strings' % e['entity_id']
    if e['origin'] not in ('source', 'editorial') or not isinstance(e['documents'], list):
        return '%s origin/documents invalid' % e['entity_id']
    mentions = e.get('mentions', [])
    if not isinstance(mentions, list) or any(m not in ctx.by_cid for m in mentions):
        return '%s mentions a content_id that is not in book.json' % e['entity_id']
    return None


def check_graph(ctx: Ctx) -> Check:
    c = Check('knowledge.graph')
    g = ctx.data.get('knowledge/graph.json')
    if not isinstance(g, dict) or not ctx.by_cid:
        return c.skip('graph.json or sections not loaded')
    if any(k not in g for k in ('edition', 'nodes', 'edges', 'entity_types', 'relation_types')):
        c.fail('needs edition/nodes/edges/entity_types/relation_types')
        return c
    rel = set()
    for r in g['relation_types'] if isinstance(g['relation_types'], list) else []:
        if not isinstance(r, str) or not re.match(r'^[A-Z][A-Z_]{1,39}$', r):
            c.fail('relation type %r invalid' % r)
        rel.add(r)
    nodes = set()
    for n in g['nodes'] if isinstance(g['nodes'], list) else []:
        c.checked += 1
        p = _entity_problem(n, ctx)
        if p:
            c.fail('node ' + p)
        elif isinstance(n, dict):
            nodes.add(n['entity_id'])
    if not nodes:
        c.fail('nodes must not be empty')
    for i, e in enumerate(g['edges'] if isinstance(g['edges'], list) else []):
        c.checked += 1
        if not isinstance(e, dict) or any(k not in e for k in ('source', 'relation', 'target', 'content_id', 'origin')):
            c.fail('edges[%d] lacks source/relation/target/content_id/origin' % i)
            continue
        if e['source'] not in nodes or e['target'] not in nodes:
            c.fail('edges[%d] endpoint is not a node' % i)
        if e['relation'] not in rel or e['origin'] not in ('source', 'editorial'):
            c.fail('edges[%d] relation/origin invalid' % i)
        if e['content_id'] not in ctx.by_cid:
            c.fail('edges[%d] content_id %s is not in book.json' % (i, e['content_id']))
        ev = e.get('evidence')
        if ev is not None and (not isinstance(ev, dict) or len(str(ev.get('quote', ''))) > 200
                               or len(str(ev.get('block_id') or '')) > 128):
            c.fail('edges[%d].evidence is unbounded' % i)
    return c


def check_entities(ctx: Ctx) -> Check:
    c = Check('knowledge.entities')
    rows = ctx.data.get('knowledge/entities.jsonl')
    if rows is None or not ctx.by_cid:
        return c.skip('entities.jsonl or sections not loaded')
    if not rows:
        c.fail('entities.jsonl is empty')
    for i, e in enumerate(rows, 1):
        c.checked += 1
        p = _entity_problem(e, ctx)
        if p:
            c.fail('line %d %s' % (i, p))
    return c


def check_rag_corpus(ctx: Ctx) -> Check:
    c = Check('release.rag_corpus')
    rows = ctx.data.get('release/14_rag_corpus_fa.jsonl')
    if rows is None or not ctx.by_cid:
        return c.skip('rag corpus or sections not loaded')
    if not rows:
        c.fail('rag corpus is empty')
    req = ('chunk_id', 'content_id', 'structural_id', 'language', 'origin', 'label_fa', 'fa_text', 'part_id',
           'chapter_id', 'section_id', 'keywords_fa', 'keywords_en', 'source_documents', 'canonical_url')
    for i, r in enumerate(rows, 1):
        c.checked += 1
        if any(k not in r for k in req):
            c.fail('line %d lacks one of the chunk fields' % i)
            continue
        s = ctx.by_cid.get(r['content_id'])
        if s is None or r['structural_id'] != s.get('structural_id'):
            c.fail('line %d content_id/structural_id is not a section of book.json' % i)
            continue
        if not re.match(re.escape(r['content_id']) + r'#r\d{1,3}$', str(r['chunk_id'])):
            c.fail('line %d chunk_id %r is not {content_id}#rNN' % (i, r['chunk_id']))
        if r['language'] != 'fa' or r['origin'] != s.get('origin'):
            c.fail('line %d language/origin mismatch' % i)
        if not non_empty(r['fa_text']) or len(r['fa_text']) > 5000:
            c.fail('line %d fa_text empty or > 5000 chars' % i)
        if r['label_fa'] is not None and (not isinstance(r['label_fa'], str) or len(r['label_fa']) > 200):
            c.fail('line %d label_fa must be null or <= 200 chars' % i)
        if [r['part_id'], r['chapter_id'], r['section_id']] != [s.get('part_id'), s.get('chapter_id'), s.get('section_id')]:
            c.fail('line %d part/chapter/section ids disagree with the section' % i)
        if not all(isinstance(r[k], list) and all(isinstance(x, str) for x in r[k])
                   for k in ('keywords_fa', 'keywords_en', 'source_documents')):
            c.fail('line %d keyword/source lists must hold strings' % i)
        if not url_ok(r['canonical_url'], ctx, fragment=r['structural_id']):
            c.fail('line %d canonical_url must be in the book namespace with #%s' % (i, r['structural_id']))
        if 'unit_content_hash' in r and r['unit_content_hash'] != s.get('content_hash'):
            c.fail('line %d unit_content_hash is stale for %s' % (i, r['structural_id']))
        if 'content_hash' in r and r['content_hash'] != 'sha256:' + hashlib.sha256(r['fa_text'].encode('utf-8')).hexdigest():
            c.fail('line %d content_hash != sha256(fa_text)' % i)
    return c


def check_search_index(ctx: Ctx) -> Check:
    c = Check('html.search_index')
    si = ctx.data.get('html/search/index.json')
    if si is None:
        return c.skip('html/search/index.json absent')
    if not ctx.by_cid:
        return c.skip('sections not loaded')
    entries = si.get('entries')
    if not isinstance(entries, list) or si.get('count') != len(entries or []):
        c.fail('count must equal len(entries)')
        entries = entries if isinstance(entries, list) else []
    if len(entries) != len(ctx.by_cid):
        c.fail('%d entries for %d sections' % (len(entries), len(ctx.by_cid)))
    req = ('id', 'structural_id', 'url', 'title_fa', 'part', 'chapter', 'origin', 'docs', 'keywords_fa',
           'keywords_en', 'acronyms', 'snippet')
    for i, e in enumerate(entries):
        c.checked += 1
        if not isinstance(e, dict) or any(k not in e for k in req):
            c.fail('entries[%d] lacks one of %s' % (i, ', '.join(req)))
            continue
        s = ctx.by_cid.get(e['id'])
        if s is None or e['structural_id'] != s.get('structural_id'):
            c.fail('entries[%d] id %s is not a section of book.json' % (i, e['id']))
        if not url_ok(e['url'], ctx, fragment=e['structural_id']):
            c.fail('entries[%d] url is not in the book namespace' % i)
        if not all(non_empty(e[k]) for k in ('title_fa', 'part', 'chapter')) or e['origin'] not in ORIGINS:
            c.fail('entries[%d] title/part/chapter/origin invalid' % i)
        if not all(isinstance(e[k], list) and all(isinstance(x, str) for x in e[k])
                   for k in ('docs', 'keywords_fa', 'keywords_en', 'acronyms')):
            c.fail('entries[%d] list fields must hold strings' % i)
        if not isinstance(e['snippet'], str) or len(e['snippet']) > 2000:
            c.fail('entries[%d] snippet must be a string <= 2000 chars' % i)
    return c


def check_pdf(ctx: Ctx) -> Check:
    c = Check('pdf.file')
    p = ctx.root / 'release/06_book_fa.pdf'
    if not p.is_file():
        return c.skip('release/06_book_fa.pdf absent')
    c.checked = 1
    size = p.stat().st_size
    if size < 1:
        c.fail('PDF is empty')
    man = ctx.data.get('provenance/release-manifest.json') or {}
    a = (man.get('artifacts') or {}).get('06_book_fa.pdf') if isinstance(man.get('artifacts'), dict) else None
    if isinstance(a, dict):
        if a.get('bytes') != size:
            c.fail('PDF is %d bytes, the release manifest says %s (the reader refuses to serve it)' % (size, a.get('bytes')))
        elif sha256_file(p) != a.get('sha256'):
            c.fail('PDF sha256 differs from the release manifest')
    c.notes.append('%.1f MB' % (size / 1048576))
    return c


CHECKS = [check_files, check_book_top, check_book_structure, check_sources, check_section_fields, check_ids,
          check_content_hashes, check_merkle, check_content_ids_registry, check_citation_registry, check_editions,
          check_release_manifest, check_overlay, check_markdown_tables, check_markdown_footnotes,
          check_markdown_figures, check_markdown_unsupported, check_doc_titles, check_glossary, check_source_map,
          check_templates, check_graph, check_entities, check_rag_corpus, check_search_index, check_pdf]


def infer_slug(ctx: Ctx):
    book = ctx.data.get('master/book.json')
    try:
        url = book['parts'][0]['chapters'][0]['sections'][0]['canonical_url']
    except (KeyError, IndexError, TypeError):
        return LEGACY_SLUG
    m = re.match(r'^https://kohandezh\.com/fa/books/([a-z0-9-]+)/', str(url))
    return m.group(1) if m else LEGACY_SLUG


def validate(root, strict=False, require_build=False, slug=None, code=None) -> dict:
    """Run every check; returns the report dict (see --json)."""
    started = time.time()
    ctx = Ctx(Path(root), strict, require_build or strict, slug, code)
    results = []
    for fn in CHECKS:
        result = fn(ctx)
        if fn is check_files and ctx.slug is None:
            ctx.slug = infer_slug(ctx)
        results.append(result.as_dict())
    if not BOOK_SLUG_RE.match(ctx.slug or '') or len(ctx.slug) > 40:
        results.append({'name': 'registry.slug', 'status': 'FAIL', 'count': 1,
                        'examples': ['slug %r breaks ^[a-z0-9]+(-[a-z0-9]+)*$ (<= 40)' % ctx.slug], 'detail': ''})
    summary = {s: sum(1 for r in results if r['status'] == s) for s in ('PASS', 'WARN', 'FAIL', 'SKIP')}
    return {'format': FORMAT, 'root': str(ctx.root), 'slug': ctx.slug, 'strict': strict,
            'require_build': ctx.require_build, 'checks': results, 'summary': summary,
            'seconds': round(time.time() - started, 2), 'exit': 1 if summary['FAIL'] else 0}


def print_report(report: dict, out=sys.stdout) -> None:
    print('%s  %s  (slug %s%s)' % (report['format'], report['root'], report['slug'],
                                  ', strict' if report['strict'] else ''), file=out)
    for r in report['checks']:
        print('  %-4s  %-32s %6d  %s' % (r['status'], r['name'], r['count'], r['detail']), file=out)
        if r['status'] in ('WARN', 'FAIL'):
            for ex in r['examples']:
                print('          - %s' % ex, file=out)
    s = report['summary']
    print('Result: %d PASS, %d WARN, %d FAIL, %d SKIP in %.1f s -> exit %d'
          % (s['PASS'], s['WARN'], s['FAIL'], s['SKIP'], report['seconds'], report['exit']), file=out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description='Validate a Kohandezh book bundle (Books/BOOK-FORMAT.md).')
    ap.add_argument('--root', default=str(REPO / 'Books' / 'ai-governance'))
    ap.add_argument('--strict', action='store_true', help='missing build or optional files are FAILs')
    ap.add_argument('--release', action='store_true', help='missing build outputs (PDF, search index) are FAILs')
    ap.add_argument('--slug', help='registry slug (default: inferred from canonical_url)')
    ap.add_argument('--code', help='ID code, e.g. AI (default: inferred)')
    ap.add_argument('--json', action='store_true', help='print the report as JSON')
    args = ap.parse_args(argv)
    root = Path(args.root)
    if not root.is_dir():
        print('validate_book: --root %s is not a directory' % root, file=sys.stderr)
        return 2
    if args.code and not CODE_RE.match(args.code):
        print('validate_book: --code must match [A-Z0-9]{1,8}', file=sys.stderr)
        return 2
    report = validate(root, args.strict, args.release, args.slug, args.code)
    if args.json:
        json.dump(report, sys.stdout, ensure_ascii=False, indent=1)
        print()
    else:
        print_report(report)
    return report['exit']


if __name__ == '__main__':
    sys.exit(main())
